= Obtaining the Client Credentials of a Registered Client Application
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As the owner of a xref:exchange::to-request-access.adoc[registered client application], you are occasionally required to provide your client ID and client secret when accessing an API, after a contract is created between your application and an API. 

You are required to provide the client ID and client secret credentials depending on the policies applied to that API. For example, if the API owner has applied the Client ID Enforcement policy, you must provide your application's client ID and, optionally, its client secret to access the API.

You must have the Organization Administrator privileges of the root organization, or must be the owner of the client application to access the credentials.  

To obtain the credentials of a client application:

. Go to *Anypoint Platform* > *API Manager*.
. Click *Client Applications*.
. From the details pane, click the application for which you want to view the client credentials.
+
The client ID and client secret credentials for the selected application appear in the window. 
. Alternatively, if you need to obtain only the client ID of the registered client application, select the correct version of the API and click *Contracts*. 
+
As an Application Owner, if you do not have access to API Manager, you can view the xref:exchange::about-my-applications.adoc[application credentials] in Exchange.
. To view the details, click the specific API contract. 

== See Also

* xref:exchange::to-request-access.adoc[Registering a Client Application]
https://docs.mulesoft.com/exchange/about-my-applications
