= Access Asset and Developer Portals
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
 
As an administrator, you can view the resources and methods of an API, and access other details, such as publish date and mocking service, from Anypoint Exchange (Exchange). You can view the API in an asset portal (private) or a public portal.

== Access an Asset Portal

Before you access an asset portal, ensure that you meet one of the following conditions:

* The portal is listed in the organization's public developer portal.
* The portal is private but you have Portals Viewer access.

To access an asset portal:

. Navigate to *API Manager* and click the *Administration* tab.
. Select the API instance that you want to access.
. From the top-right corner on the API instance page, click *View API in Exchange*.
+
The portal for the selected asset is displayed in an Exchange window. You can also share and make the xref:exchange::about-portals.adoc[portal public] in Anypoint Exchange.

== Access a Public Portal 

To access an organization's public portal:

. Navigate to *Exchange* > *Public portal*.
. From the developer portal page, select the asset that you want to access.



== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/[Anypoint Platform developer portal]
* xref:access-management::roles.adoc#default-roles[Portals Viewer]