= Access the Developer Portal
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As an administrator, you can view API portals if you have the appropriate access. The public https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[Anypoint Platform developer portal], enables you to automate Anypoint Platform activities.
 
You can view an API portal in Anypoint Platform if:

* The portal is listed in the organization's public developer portal
* You are granted Portals Viewer access for a portal 


To access your organization's Anypoint Platform developer portal:

. Go to *API Manager* > *Administration* tab.
. Select the API instance that you want to view in the developer portal.
. From the top-right corner on the API instance page, click *View API in Exchange*.
+
The Developer portal for the selected asset is displayed in a new window. You can also share and make the xref:exchange::about-portals.adoc[portal public] in Anypoint Exchange.
 

== See Also

* https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[Anypoint Platform developer portal]
* xref:access-management::roles.adoc#default-roles[Portals Viewer]