= Access API Instance and Developer Portals
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
 
As an administrator, you can view an API portal: public(https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/[developer portal]) and API instance portal in Anypoint Platform if either of the following conditions exist:

* The portal is listed in the organization's public developer portal.
* The portal is private but you have Portals Viewer access.

== Access a Public Portal 

To access an organization's public portal:

. Navigate to *Exchange* > *Public portal*.
. From the developer portal page, select the asset that you want to access.

== Access API Instance Portal
//Access a Private [[API Instance?]] Portal

To access an API instance portal:

. Navigate to *API Manager* and click the *Administration* tab.
. Select the API instance that you want to access.
. From the top-right corner on the API instance page, click *View API in Exchange*.
+
The portal for the selected asset is displayed in a new window. You can also share and make the xref:exchange::about-portals.adoc[portal public] in Anypoint Exchange.

== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/[Anypoint Platform developer portal]
* xref:access-management::roles.adoc#default-roles[Portals Viewer]