= To Add an API Alert
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You deploy the API version before attempting to add an alert.

. In API Administration, select an API version, and on the API version details page, select Alerts.
. Click Add Alert and set the alert options:
* Name: Type an alert name, for example `red-alert`.
* Enabled: Accept the default, Enabled, for example.
* Severity: Accept the default, Critical.
* Api: Select the name of an API. For example, `jsonplaceholderapi`.
* Api version: Select a version. For example, 1.0.
* Alert type: Select Request Count, for example.
* When number of occurrences are: Select Greater.
* than: Select 1.
* For at least: Select an entry in the range 1 - 999999999 to specify the time intervals as a sliding windows.
* Recipients: Select the names of users in your business group, or type the email addresses, of users who will receive notification when the alert fires. Press RETURN.
+
. Create the alert.

== See Also

* https://www.techopedia.com/definition/869/sliding-window[Sliding windows]