= Add API Alerts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To track and manage APIs, you can add one or more API alerts to your API instances. Add different xref:using-api-alerts.adoc[types of alerts] based on your requirements.

[NOTE]
====
Alerts cannot be added to API instances protected by xref:automated-policies-landing-page.adoc[automated policies].
====

To add an API alert:

. Navigate to *API Manager* > *API Administration* and click the API instance for which you want to add an alert.
. From the left navigation pane, select *Alerts* > *Add alert*.
. Specify the alert options:
* *Name*: 
+
Type an alert name, for example `trial-alert`.
* *Enabled*: 
+
The default option is *Enabled*.
+
You can delete an alert anytime if not required.
* *Severity*: 
+
Select a severity for the alert, for example, *Info*.
* *Alert type*: 
+
Select the type of alert to create, (for example, *Request Count*) and provide appropriate alert configuration values.
+
[TIP]
====
In the *For at least* and *consecutive period(s) of* fields, enter a value in the range of 1 - 999999999 to specify the time interval as a https://www.techopedia.com/definition/869/sliding-window[sliding window^].
====

. Select *Create Alert*.

== See Also

* xref:using-api-alerts.adoc[Review Alerts Concepts]
