= Add Instance Alerts for Mule Gateway or Service Mesh
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To track and manage instances, you can add one or more alerts to your instances. Add different xref:using-api-alerts.adoc[types of alerts] based on your requirements. 

For instances using Mule Gateway or Anypoint Service Mesh as their runtime, follow the steps in this tutorial to add alerts. 

You cannot add Policy Violation alerts to xref:automated-policies-landing-page.adoc[automated policies].

NOTE: This tutorial is for Mule Gateway and Anypoint Service Mesh runtimes. To add alerts to instances using Flex Gateway as their runtime, see xref:gateway::flex-use-api-alerts.adoc[Add Instance Alerts for Flex Gateway].

[[mule-gateway]]
== Add Instance Alerts for Mule Gateway or Anypoint Service Mesh
To add an alert to a Mule Gateway or Anypoint Service Mesh instance:

. Navigate to *Anypoint Platform* > *API Manager*.
. In *API Administration*, click the instance to which to add an alert.
. Click *Alerts* > *Add alert*.
. Specify the alert options:
* *Name*: 
+
Type an alert name, for example `trial-alert`. 
+
If adding multiple alerts to the same environment, the alerts must have unique names.
* *Enabled*: 
+
The default option is *Enabled*.
+
You can delete an alert anytime if not required.
* *Severity*: 
+
Select a severity for the alert, for example, *Info*.
* *Alert type*: 
+
Select the type of alert to create, (for example, *Request Count*) and provide appropriate alert configuration values. For information about alert types, see xref:using-api-alerts.adoc#api-alerts[Instance Alerts].
+
[TIP]
====
In the *For at least* and *consecutive period(s) of* fields, enter a value in the range of 1 - 999999999 to specify the time interval as a https://www.techopedia.com/definition/869/sliding-window[sliding window^].
====

. Select *Recipients*.
+
Specify what emails receive the email notification.

. Click *Create Alert*.


== See Also

* xref:using-api-alerts.adoc[Review Alerts Concepts]
* xref:gateway::flex-use-api-alerts.adoc[]
