= Add API Alerts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To track and manage APIs, you can add one or more API alerts to your API instances. Add different xref:using-api-alerts.adoc[types of alerts] based on your requirements. Adding alerts is different for API Instances using Mule Gateway or Flex Gateway Connected Mode as there runtime. See the following to add API alerts for your runtime:
* <<mule-gateway, Add API Alerts for Mule Gateway>>
* <<flex-gateway, Add API Alerts for Flex Gateway>>

[NOTE]
====
Alerts cannot be added to API instances protected by xref:automated-policies-landing-page.adoc[automated policies].
====

[[mule-gateway]]
== Add API Alerts for Mule Gateway
To add an API alert for a Mule Gateway API:

. Navigate to *API Manager* > *API Administration* and click the Mule API instance for which you want to add an alert.
. From the left navigation pane, select *Alerts* > *Add alert*.
. Specify the alert options:
* *Name*: 
+
Type an alert name, for example `trial-alert`.
* *Enabled*: 
+
The default option is *Enabled*.
+
You can delete an alert anytime if not required.
* *Severity*: 
+
Select a severity for the alert, for example, *Info*.
* *Alert type*: 
+
Select the type of alert to create, (for example, *Request Count*) and provide appropriate alert configuration values.
+
[TIP]
====
In the *For at least* and *consecutive period(s) of* fields, enter a value in the range of 1 - 999999999 to specify the time interval as a https://www.techopedia.com/definition/869/sliding-window[sliding window^].
====

. Select *Recipients*.
. Select *Create Alert*.

[[flex-gateway]]
== Add API Alerts for Flex Gateway
To add an API alert for a Flex Gateway API:

== See Also

* xref:using-api-alerts.adoc[Review Alerts Concepts]
