= Add API Alerts for Mule Gateway or Service Mesh
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To track and manage APIs, you can add one or more API alerts to your API instances. Add different xref:using-api-alerts.adoc[types of alerts] based on your requirements. 

For APIs using Mule Gateway or Service Mesh as their runtime, follow the steps in this tutorial. 

You cannot add Policy Violation alerts to xref:automated-policies-landing-page.adoc[automated policies].

NOTE: This tutorial is on for Mule Gateway or Service Mesh runtimes. To add alerts to APIs using Flex Gateway as their runtime, see xref:gateway::flex-use-api-alerts.adoc[Add API Alerts for Flex Gateway].

[[mule-gateway]]
== Add API Alerts for Mule Gateway or Service Mesh
To add an API alert to a Mule Gateway or Service Mesh API:

. Navigate to *API Manager > API Administration* and click the API instance for which you want to add an alert.
. From the left navigation panel, click *Alerts > Add alert*.
. Specify the alert options:
* *Name*: 
+
Type an alert name, for example `trial-alert`.
* *Enabled*: 
+
The default option is *Enabled*.
+
You can delete an alert anytime if not required.
* *Severity*: 
+
Select a severity for the alert, for example, *Info*.
* *Alert type*: 
+
Select the type of alert to create, (for example, *Request Count*) and provide appropriate alert configuration values. For information about alert types, see xref:using-api-alerts.adoc#api-alerts[API Alerts].
+
[TIP]
====
In the *For at least* and *consecutive period(s) of* fields, enter a value in the range of 1 - 999999999 to specify the time interval as a https://www.techopedia.com/definition/869/sliding-window[sliding window^].
====

. Select *Recipients*.
+
Specify what emails receive the email notification.

. Click *Create Alert*.


== See Also

* xref:using-api-alerts.adoc[Review Alerts Concepts]
* xref:gateway::flex-use-api-alerts.adoc[Add API Alerts for Flex Gateway]
