= OAuth 2 Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Anypoint Platform, you can work with OAuth solutions on both the server side, for example, by configuring an HTTP or Salesforce connector to access an OAuth-protected server, and the client side, for example, by applying an OAuth 2.0 policy and and enforce authentication from your client applications through your own OAuth provider.

You can use the following OAuth provider and policy pairs:

[%header,cols="40a,60a"]
|===
| Provider | Policy Name
| PingFederate | PingFederate OAuth Token Enforcement.
| OpenAM | OpenAM OAuth Token Enforcement.
| A Dynamic Client Registration-compliant identity provider  | OpenID Connect Access Token Enforcement.
| Mule OAuth 2.0 Access Token Enforcement | OAuth 2.0 Access Token Enforcement Using External Provider.
|===

The Dynamic Client Registration-compliant identity provider needs to conform to the OpenID Connect Client Registration 1.0 incorporating errata set 1.

The API to which you apply an OAuth 2.0 policy supports HTTPS communication using a Mule OAuth 2.0 provider. The provider verifies the validity of OAuth 2.0 credentials.

== See Also

* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1]
* xref:external-oauth-2.0-token-validation-policy.adoc[OAuth 2.0 Access Token Enforcement Using External Provider]
* xref:access-management::external-identity.adoc[SAML 2.0 and OpenID Connect providers]
