= Alerts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: alert

Alerts in Anypoint Platform notify you about unusual behavior or performance, actions related to client application contracts, and runtime events. The platform supports three types of alerts: API alerts, contracts alerts, and runtime alerts. API alerts and contracts alerts are managed by API Manager. Runtime alerts are managed by Runtime Manager.

== API Alerts
 
In API Manager, you can configure alerts that flag unusual API-specific behavior, such as if the response time of an API is greater than 60 seconds, or if the number of API requests in 30 seconds is greater than 1000. These alerts are referred to as API alerts. See xref:add-api-alert-task.adoc[Adding an API Alert].

API Manager enables you to add the following types of API alerts to an API instance:

* *Policy Violation*
+
An infraction of one or more policies that govern the API occurs.

* *Request Count*
+
Users request access to the API more times than allowed in a specified interval of time.
+
Time interval values are in the range 1 - 999999999. The intervals are implemented as sliding windows, not absolute minute boundaries, to prevent data burst problems. See https://www.techopedia.com/definition/869/sliding-window[Sliding windows].

* *Response Code*
+
The API returns one of these HTTP codes upon receiving a request: 400, 401, 403, 404, 408, 500, 502, or 503

* *Response Time*
+
The response time of the API exceeds a specified period. 

API Manager triggers API alerts only when states change. However the first occurrence of a state change may be undetected because newly created alerts have undefined states.

When configuring an API alert, you select Business Group users who can receive email notifications about the alert. The notification includes information about events that trigger the alert as specified by the level of severity. Users receive two emails:

* One email describes the alert. For example:
+
`Your API, CesarDemoAPI - Basic:151 (Environment: "NewOne"), has received greater than 2 requests within 1 consecutive periods of 1 minutes.`
+
* Another email notifies you when the alert is resolved.
+
`Your API Version, jsonplaceholderapi - 1.0.development, is no longer in an alert state. The number of policy violations was not greater than 1 in the last 1 consecutive periods of 1 minutes.`

After an alert is triggered, API Manager sends the first set of two notification emails, and stops listening for alerts until the next alert period begins. This technique prevents repetitive notification emails.

== Contracts Alerts

API Manager automatically notifies users when actions related to contracts occur. For example, when a client application requests access to an API instance, API Manager sends a notification indicating that the request access is pending (or that the request access has been auto-approved, depending on the configuration).

The following tables list actions that trigger contracts alerts, and who receives the related notifications:

.Contracts
[%header]
|===
| Action | Recipient | Description
| Contract approved
| Client application owners
| User will be notified that request access was approved.

| Contract auto-approved
| Organization administrators, environment administrators, contracts managers
| User will be notified that request access was auto-approved.

| Contract pending
| Organization administrators, environment administrators, contracts managers
| User will be notified that request access is pending.

| Pending contract rejected
| Client application owners
| User will be notified that request access was rejected.

| Revoked contract restored
| Client application owners
| User will be notified that request access was restored.

| Approved contract revoked
| Client application owners
| User will be notified that request access was revoked.

| Contract tier changed
| Client application owners
| User will be notified that the contract tier was changed.

| Requested contract tier change approved
| Client application owners
| User will be notified that a requested tier change was approved.

| Requested contract tier change rejected
| Client application owners
| User will be notified that a requested tier change was rejected.

| Contract tier change requested
| Organization administrators, environment administrators, contracts managers
| User will be notified that a contract tier change is pending review.
|===

.Group Contracts
[%header]
|===
| Action | Recipient | Description
| Contract approved
| Client application owners
| User will be notified that request access was approved.

| Contract auto-approved
| Group administrators
| User will be notified that request access was auto-approved.

| Approved contract revoked
| Client application owners
| User will be notified that request access was revoked.

| Revoked contract restored
| Client application owners
| User will be notified that request access was restored.

| Pending contract rejected
| Client application owners
| User will be notified that request access was rejected.

| Contract pending
| Group administrators
| User will be notified that request access is pending.

| Contract tier changed
| Client application owners
| User will be notified that a contract tier change is pending review.

| Requested contract tier change approved
| Client application owners
| User will be notified that a requested tier change was approved.

| Requested contract tier change rejected
| Client application owners
| User will be notified that a requested tier change was rejected.

| Contract tier change requested
| Group administrators
| User will be notified that a contract tier change is pending review.
|===

== Runtime Alerts
Alerts in Runtime Manager differ from API alerts and contracts alerts. For example, Runtime Manager flags CPU usage, secure data gateway status, and deployment success or failure. See xref:runtime-manager::alerts-on-runtime-manager.adoc[Runtime Manager Alerts].

== See Also

* xref:add-api-alert-task.adoc[Adding an API Alert]
* xref:test-alert-task.adoc[Testing an API Alert]
* xref:view-delete-alerts-task.adoc[Viewing and Deleting API Alerts]
* xref:edit-enable-disable-alerts-task.adoc[Editing, Enabling, or Disabling API Alerts]