= Mule API Analytics
include::partial$analytics-eol.adoc[]
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: analytics
:page-aliases: analytics-concept.adoc

NOTE: *Mule API Analytics* does not support Omni Gateway APIs. For Omni Gateway Analytics, see xref:gateway::flex-view-api-metrics.adoc[].

Mule API Analytics can provide insight into how your Mule APIs are being used and how they are performing. From API Manager, you can access the Mule API Analytics dashboard, create a custom dashboard, create and manage charts, and create reports. From API Manager, you can get following types of analytics:

* API viewing analytics
* API events analytics
* Charted metrics in API Manager

You can view data from a policy perspective in the Mule API Analytics dashboard, Mule API Analytics chart, or API Manager by including policy violations. This action tracks traffic rejected, or not rejected, by a policy.

The *Mule API Analytics* tab is visible only to users who have `View APIs Configuration` permission. Charts are visible for users who have `View APIs Configuration` permission.

[NOTE]
API Analytics isn't available on Hyperforce deployments.


== See Also

*** xref:viewing-api-analytics.adoc[Reviewing Analytics usage]
*** xref:analytics-chart.adoc[View Mule API Analytics Charts in API Manager]
*** xref:analytics-event-api.adoc[Generate Mule API Analytics Reports with the Event API]
*** xref:analytics-event-forward.adoc[Forward Mule API Analytics Events to External Systems]
