= Reviewing Analytics
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: analytics, faq

== Why does "No API requests for this time period" display?

Your API request should display. Check these:

* Is your API tracked (is the green dot displayed?)?

* Is the policy requiring Client ID and Client Secret actually applied? For example, try calling your endpoint without those values and check that the response code is the expected one (for example, 4xx).

* When you turn off your API Manager instance, do you see the orange dot that indicates that the API is not tracked anymore? If it continues to be tracked, then your API Manager is likely misconfigured.

You can also enable DEBUG or TRACE level for Analytics in the ../src/main/resources/log4j2.xml file for your project.

Check your logs for one or both of these messages, which can indicate that the events were successfully set to the Analytics API:

----
"Sent [n] events to analytics ingest."
"[n] policy violation events were sent to analytics ingest"
----

If these messages are not present, check the application's log to see that you see both of the following messages:

----
"New message received notification..."
"New message response notification... "
----

In previous versions of Anypoint Data Gateway, an issue prevented RAML/OAS type proxies from working correctly. Ensure that you have the latest software where this issue has been fixed.

You may need to create a Custom Report that lists the API response status code, status message, IP address, and any other information you need.

== Why is my data not showing in my dashboard immediately?

Analytics data typically takes up to 5 minutes to appear.
