= API Analytics
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: analytics

API Analytics can provide insight into how your APIs are being used and how they are performing. From API Manager, you can access the Analytics dashboard, create a custom dashboard, create and manage charts, and create reports. From API Manager, you can get following types of analytics:

* API viewing analytics
* API events analytics
* Charted metrics in API Manager

You can view data from a policy perspective in the Analytics dashboard, Analytics chart, or API Manager by including policy violations. This action tracks traffic rejected, or not rejected, by a policy.

*Note:* The Analytics link is visible only to users who have Environment Admin permission. Charts are visible for users with View APIs Configuration permission.

== See Also

*** xref:environment-permission-task.adoc[Setting Permissions]
*** xref:viewing-api-analytics.adoc[Viewing Analytics]
*** xref:analytics-event-api.adoc[Analytics Event API]
*** xref:analytics-chart.adoc[Chart in API Manager]
*** xref:analytics-event-forward.adoc[About Event Forwarding]