= SLA Tiers For API Groups
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can specify service-level agreement (SLA) tiers to API Groups instances to limit the number of requests an application (user) can make to the APIs grouped in a product. SLAs enable you to protect your API Group instances and help manage network traffic to your APIs.

The SLA tier definition also determines whether access to the API Groups instance requires your approval. You can configure manual or automatic approvals to requests.

== SLA Types

SLA tiers are of two types: 

* Default SLAs
* Individual API SLAs

== Default 

The default limit is set by the product administrator and applies to all API instances. If you add a new API instance to an API group instance, the default limit SLA configured at the group instance level applies, unless an individual API SLA tier set by the Product Administrator. 

//Do we have a role called Product Administrator?I did not see this in this in the system.

== Individual API SLAs

As a Product Administrator, you can define individual limits for API instances within an API Group instance.  If you have configured a default SLA limit at the API Group instance level and an individual SLA limit at the API instance lvel, the individual SLA takes precedence over the defalt limit. 

If no individual SLA is set, then the default SLA limit is enforced for that API instance.

If the Rate Limiting policy is applied on an API instance, as a Product Administrator you must determine if the new SLA can be fulfilled by the underlying API instance. 

== Manual and Automatic Approvals

When you configure automatic approvals for an SLA tier, requests made to the API instances with that tier applied are automatically approved. Consumers can instantaneously use API Group instances in this case.

Manual approvals are routed through a manual approval flow, where the API Group owner must manually approve the consumer request. These approvals can take time.

== Layered SLAs

API Groups supports multiple SLA limits. You can set multiple throughput limits for a single SLA tier. A single SLA tier named `Premium` can limit requests to 100 per second as well as limiting requests to 10,000 per day. 

This strategy ensures that applications registered on a `Premium` tier does not exceed the top limit of 100 requests per second. This way, applications do not inundate the API, and registered applications get the expected 10,000 request per day. 



