= Gateway Startup Encryption in Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Gateway startup encryption allows you to encrypt sensitive information required to configure the connection between your Mule application and Anypoint Platform. You can use it to secure your client id, client secret, and your proxy password.

== Encrypting Values using the Agent

Configuring encryption through the Runtime Manager Agent is the fastest way to secure your client credentials. You have to add the encryption key when creating an Agent server, and the agent will handle the properties encryption for you. +
See xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[Install and Configure the Runtime Manager Agent] to learn how to configure the agent with encryption.

== Encrypting the Client ID and Secret

If you are not using an agent, you can still manually encrypt your properties.

The most common way, is using the xref:mule-rutime::secure-configuration-properties.adoc#secure-properties-tool[Secure Properties Tools]. +
When using encrypted properties, the API gateway assumes that you are using the AES algorithm in CBC Mode.

=== Example

Suppose that your client ID is `bb458e566cba4e2ea5a826d27b46031a`, and that you choose the encryption key to be the 128 bits string `MyEncryptionKey1`. To encrypt it, you need to run the following command:

// tag::example[]
[source,console,linenums]
--
> java -jar secure-properties-tool.jar \
string \ //<1>
encrypt \ //<2>
AES \ //<3>
CBC \
MyEncryptionKey1 \ //<4>
bb458e566cba4e2ea5a826d27b46031a
--

<1> As you are trying to encrypt a single value, you need to specify it using the string parameter.
<2> Set the tool to encrypt the value.
<3> Use AES with CBC Mode. +
This is important, as the runtime only uses this configuration to later decrypt the value.
<4> And finally, you write your encryption key and the value you want to encrypt.
// end::example[]

This command outputs your encrypted client ID:

[source,console,linenums]
--
> smzbg+aV2HbiC9Fv8KBsZpD5PlXiplsfhZ42RWNEbHhUeZ9ZIDftljUx6sYpuQ+b
--

== Passing your Encrypted Client ID and Secret

After encrypting your credentials, you need to configure your encrypted values in your `wrapper.conf` file located inside the `conf` directory in the root folder of your Mule runtime:

[source]
--
anypoint.platform.client_id
anypoint.platform.client_secet
anypoint.platform.proxy_password
--

In the example above, your `client_id` would look as below:

[source]
--
anypoint.platform.client_id=![smzbg+aV2HbiC9Fv8KBsZpD5PlXiplsfhZ42RWNEbHhUeZ9ZIDftljUx6sYpuQ+b]
--

[NOTE]
The `![` prefix and  `]` suffix are required, as they indicate the runtime that the enclosed value is encrypted.

For the runtime to be able to decrypt your secured values, you need to also configure your secret key using the `anypoint.platform.encryption_key` property in the wrapper file:

[source]
--
anypoint.platform.encryption_key=MyEncryptionKey1
--

== How It Works

When starting, the runtime checks for an encryption key. +
When you provide a key, the runtime displays the following message:

[source]
--
An encryption key is present. Policies and API contracts will be encrypted.
--

If not, the runtime stars with:

[source]
--
No encryption key provided. Policies and API contracts won't be encrypted.
--

The runtime gets the client ID/client secret values from its `wrapper.conf` file. Then it checks if some of the values are enclosed within the encryption indicators (the `![` and `]` characters described above). For those being encrypted, the runtime needs to decrypt them so it can use the original value. +
To decrypt the properties, the runtime uses the encryption key configured in the `anypoint.platform.encryption_key` property.

If the decryption process fails, the runtime displays an error:

[source]
--
Client ID cannot be decrypted
--

If your credentials can't be decrypted, you cannot establish a connection with Platform, and won't be able to download policies or contracts.

=== Troubleshooting Credentials

If you run into issues when passing your encrypted credentials to Anypoint Platform, it's recommended to check that the provided credentials are valid. You can use the Secure Properties Tool described earlier to decrypt the values back to the originals and compare them with the ones displayed in the platform platform:

. Run the Secure Properties Tool to decrypt your credentials:
+
[source]
--
> java -jar secure-properties-tool.jar string decrypt AES CBC <yourEncryptionKey> <>
--
+
. Compare the decrypted value with the one in Anypoint Platform. +
See xref:org-credentials-config-mule4.adoc#obtaining-credentials[Obtaining Credentials] for information on how to verify your platform's credentials.

== Supported Properties

The following `wrapper.conf` properties support encryption:

[%header%autowidth.spread,cols="a,a,a"]
|===
Property | | Description
| Client ID | `anypoint.platform.client_id` | Your Platform Client ID
| Client Secret | `anypoint.platform.client_secet` | Your Platform Client Secret
| Proxy Password | `anypoint.platform.proxy_password` | Password of the proxy configuration to connect to Platform
|===

== Policies Encryption

The configuration for your API policies is stored in the `policies` directory, and some policies may contain sensitive information that you want to hide from unauthorized parties, such as the password field for the `Basic Authentication` header. +
Sensitive values in your provided API policies are marked as such in the API Manager UI for policy configuration. When creating a custom policy, you can define which values are sensitive.

== Configuring Policy Encryption

To enable encryption in policies, you need to provide two system properties in your `wrapper.conf` file:
* `anypoint.platform.encryption_key`. +
The encryption key for your policy.
+
[CAUTION]
--
If you already have all your policies encrypted and then needed to restart the runtime without an encryption key, all policies will be downloaded again and all the sensitive information won't be encrypted.
--
* `anypoint.platform.encryption_mode`. +
This property can take two values:
+
[%header%autowidth.spread,cols="a,a"]
|===
| `FULL` | All values are encrypted.
| `SENSITIVE_ONLY` | Only values that you marked as `sensitive` are encrypted.
|===
+
You can change the encryption mode after applying one. The files in your `policies` directory will regenerate according to your new encryption mode.
+
[CAUTION]
--
If you are changing from `FULL` to `SENSITIVE_ONLY`, any parameter not marked as `sensitive` will be shown as plain text in your filesystem.
--





== Policies That Support Encryption

Below is a list of all policies that support encryption in their values, along with their minimum required version to support this feature. +
Earlier versions of these policies, and policies not listed below will not encrypt the policies values even when the gateway capability detects and encryption key in its configuration.

[%header%autowidth.spread,cols="a,a"]
|===
| Basic Authentication | 1.2.0 and later.
| Client ID Enforcement | 1.2.0 and later.
| Header Injection | 1.1.0 and later.
| IP Whitelist | 1.2.0 and later.
| IP Blacklist | 1.2.0 and later.
| JWT Validation | 1.1.0 and later.
| Open AM | 1.2.0 and later.
| Open ID | 1.2.0 and later.
| OAuth 2.0 | 1.2.0 and later.
| Ping Federate | 1.2.0 and later.
|===

== Custom Policy Encryption

The recommended way of creating a custom policy from scratch is using the Maven archetype. +
//TODO: Add parameter and link to archetype creation task

If you are developing a custom policy manually, or want to add encryption to an existing policy, follow the steps below:

. Add the required dependencies in the policy `pom.xml` file. +
You need to add the *Secure Configuration Property Module* dependency in your `pom.xml` file:
+
[source,XML,linenums]
--
<dependency>
   <groupId>com.mulesoft.modules</groupId>
   <artifactId>mule-secure-configuration-property-module</artifactId>
   <version>${securePropertyModuleVersion}</version>
   <classifier>mule-plugin</classifier>
</dependency>
--
. Add the *Secure Properties Element* to your policy's template file. +
Paste the following snippet in your policy's XML template file, after your `<mule ...>` element:
+
[source,XML,linenums]
--
{{#if encrypted}}
<secure-properties:config key="${anypoint.platform.encryption_key}" file="${encryptedPropertiesFile}" name="encryptionConfiguration">
   <secure-properties:encrypt algorithm="AES" mode="CBC"/>
</secure-properties:config>
{{/if}}
--
+
This feature supports only the AES Algorithm in CBC mode. +
The gateway capability takes the `anypoint.platform.encryption_key` and `encryptedPropertiesFile` values from the system properties that you set at startup time for the gateway.
. Define the sensitive values in the policy's YAML file. +
By default, the values in a custom policy are not sensitive. You can define wether a value is sensitive or not In the YAML file describing your policy you can define which values are sensitive using the boolean element `sensitive`:
+
[source,YAML,linenums]
--
  configuration:
   - propertyName: username
     type: string
     sensitive: false
   - propertyName: password
     type: string
     sensitive: true //<1>
--
<1> The `password` value in your policy is now considered sensitive.

== Offline Policies Encryption

You can encrypt the configuration of your offline policies by encrypting their values using the xref:mule-rutime::secure-configuration-properties.adoc#secure-properties-tool[Secure Properties Tools] as described in the above:

include::api-manager:ROOT:page$api-gateway-encryption-mule4.adoc[tag=example]

See xref:offline-policy-task.adoc[Applying an Offline Policy] for more information.

== Contracts Encryption

If your gateway is configured with encryption, then contracts associated to contract enforcement policies will also be encrypted.

== Scope and Considerations

In a cluster scenario, you must set the encryption properties for each node. Otherwise, you may leave some of your nodes unprotected.


