= Managing API Instances
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: api, instance, manager

An API Instance is a proxy of an API that serves the upstream. API instances support the application of policies
and can be deployed to an API gateway. You can create, import, and deprecate API instances using API Manager. You can use instances of an API in multiple environments. You can also have multiple instances of an API in the same environment.

You can create one instance of an API version that serves as a proxy and create another to manage directly as an endpoint. You can apply policies to the API based on how the API is configured--proxy or endpoint. For example, you can apply caching policies to the proxy, and throttling policies and security policies to the endpoint. Additionally, you can promote an API to another environment.

NOTE: If you are running an API with a standalone server, use the xref:create-new-api-task.adoc[classic API creation flows]
to manage your API.

To manage API Instances in API Manager:

* **Step 1:** xref:create-instance-task.adoc[Add an API Instance].
* **Step 2:** xref:configure-api-task.adoc[Configure the API Instance by adding endpoint details and other settings].
* **Step 3:** Access an API Instance for information about the instance or to export it.
** xref:find-api-id-task.adoc[Obtain API Instance ID]
** xref:export-api-latest-task.adoc[Export an API Instance]
** xref:access-developer-portal-task.adoc[Access the Developer Portal]
* **Step 4:** Modify an API Instance when you no longer need the instance or it needs to
be updated to the latest version.
** xref:deprecate-api-latest-task.adoc[Deprecate an API Instance]
** xref:delete-api-task.adoc[Remove an API Instance]
** xref:manage-versions-instances-concept.adoc[Managing API Versions]
* **Step 5:** Explore advanced Use Cases for API Instances
** xref:configure-multiple-credential-providers.adoc[Configure Multiple Client Providers]
