= Deprecate API Groups
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you created a more recent version of an API Group that better suits your business needs, you might want to deprecate the older version of that same API Group. 

Deprecating an API Group from API Manager does not deprecate the API Group asset in Exchange. To deprecate an asset in Exchange, see xref:exchange::to-deprecate-asset.adoc[to deprecate asset].

=== To deprecate a Product:

. From the left menu in API Manager, click API Groups.
. Select the version of the API Group that you want to deprecate.
. From the top-right corner of the window, click the ellipses button, and select Deprecate.

== See Also
 * xref:api-groups-landing-page.adoc[API Products]
  * xref:api-groups-creating-groups.adoc[Creating Products]
 * xref:api-groups-modifying-groups.adoc[Modifying Products]
* xref:api-groups-publishing-to-exchange.adoc[Publishing Products to Exchange]
* xref:api-groups-deleting-groups.adoc[Deleting Products]