= Create API Groups
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You cab bundle a set of APIs to enable ease-of-use and efficiency for your API consumers. To create a bundle, you first create an API Group and then add the relevant API instances to it. If you want you API Group to be discovered by consumers, you must publish it to Exchange.

== Task Prerequisites

Before you begin, you must have:

* At least one API instance in your organization or business group.
* API Group Administrator permissions for all the business groups and environments in which your API instances are located. 
+
Otherwise, you may not find the required organization or business group in the list.


=== Create an API Groups

To create API Groups:

. From the left menu in API Manager, click API Groups > Create API Groups.
The Create New Product window appears.
. In the Name field, specify a name for the Product that you want to create: for example, social-media.
. In the Version field, specify the version for the Product, for example, `v1`.
. Click OK.
You are now ready to add API instanes to the product. For more information about how to add API instances to a Product, see xref:api-products-modifying-products.adoc#adding-api-instances [Adding API instances].



== See Also
 * xref:api-products-landing-page.adoc[API Groups]
 * xref:api-products-modifying-products.adoc[Modifying API Groups]
* xref:api-products-publishing-to-exchange.adoc[Publishing API Groups to Exchange]
* xref:api-products-deprecating-products.adoc[Deprecating API Groups]
* xref:api-products-deleting-products.adoc[Deleting API Groups]

