= Gateway Startup Encryption in Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Gateway startup encryption allows you to encrypt sensitive information required to configure the connection between your Mule application and Anypoint Platform. You can use it to secure your client id, client secret, and your proxy password.

== Encrypting Values using the Agent

Configuring encryption through the Runtime Manager Agent is the fastest way to secure your client credentials. You have to add the encryption key when creating an Agent server, and the agent will handle the properties encryption for you. +
See xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[Install and Configure the Runtime Manager Agent] to learn how to configure the agent with encryption.

== Encrypting the Client ID and Secret

If you are not using an agent, you can still manually encrypt your properties.

The most common way, is using the xref:mule-rutime::secure-configuration-properties.adoc#secure-properties-tool[Secure Properties Tools]. +
When using encrypted properties, the API gateway assumes that you are using the AES algorithm in CBC Mode.

=== Example

Suppose that your client ID is `bb458e566cba4e2ea5a826d27b46031a`, and that you choose the encryption key to be the 128 bits string `MyEncryptionKey1`. To encrypt it, you need to run the following command:

[source,console,linenums]
--
> java -jar secure-properties-tool.jar \
string \ //<1>
encrypt \ //<2>
AES \ //<3>
CBC \
MyEncryptionKey1 \ //<4>
bb458e566cba4e2ea5a826d27b46031a
--

<1> As you are trying to encrypt a single value, you need to specify it using the string parameter.
<2> Set the tool to encrypt the value.
<3> Use AES with CBC Mode. +
This is important, as the runtime only uses this configuration to later decrypt the value.
<4> And finally, you write your encryption key and the value you want to encrypt.

This command outputs your encrypted client ID:

[source,console,linenums]
--
> smzbg+aV2HbiC9Fv8KBsZpD5PlXiplsfhZ42RWNEbHhUeZ9ZIDftljUx6sYpuQ+b
--

== Passing your Encrypted Client ID and Secret

After encrypting your credentials, you need to configure your encrypted values in your `wrapper.conf` file located inside the `conf` directory in the root folder of your Mule runtime:

[source]
--
anypoint.platform.client_id
anypoint.platform.client_secet
anypoint.platform.proxy_password
--

In the example above, your `client_id` would look as below:

[source]
--
anypoint.platform.client_id=![smzbg+aV2HbiC9Fv8KBsZpD5PlXiplsfhZ42RWNEbHhUeZ9ZIDftljUx6sYpuQ+b]
--

[NOTE]
The `![` prefix and  `]` suffix are required, as they indicate the runtime that the enclosed value is encrypted.

For the runtime to be able to decrypt your secured values, you need to also configure your secret key using the `anypoint.platform.encryption_key` property in the wrapper file:

[source]
--
anypoint.platform.encryption_key=MyEncryptionKey1
--

== How It Works

When starting, the runtime checks for an encryption key. +
When you provide a key, the runtime displays the following message:

[source]
--
An encryption key is present. Policies and API contracts will be encrypted.
--

If not, the runtime stars with:

[source]
--
No encryption key provided. Policies and API contracts won't be encrypted.
--

The runtime gets the client ID/client secret values from its `wrapper.conf` file. Then it checks if some of the values are enclosed within the encryption indicators (the `![` and `]` characters described above). For those being encrypted, the runtime needs to decrypt them so it can use the original value. +
To decrypt the properties, the runtime uses the encryption key configured in the `anypoint.platform.encryption_key` property.

If the decryption process fails, the runtime displays an error:

[source]
--
Client ID cannot be decrypted
--

If your credentials can't be decrypted, you cannot establish a connection with Platform, and won't be able to download policies or contracts.

=== Troubleshooting Credentials

If you run into issues when passing your encrypted credentials to Anypoint Platform, it's recommended to check that the provided credentials are valid. You can use the Secure Properties Tool described earlier to decrypt the values back to the originals and compare them with the ones displayed in the platform platform:

. Run the Secure Properties Tool to decrypt your credentials:
+
[source]
--
> java -jar secure-properties-tool.jar string decrypt AES CBC <yourEncryptionKey> <>
--
+
. Compare the decrypted value with the one in Anypoint Platform. +
See xref:org-credentials-config-mule4.adoc#obtaining-credentials[Obtaining Credentials] for information on how to verify your platform's credentials.

== Supported Properties

The following `wrapper.conf` properties support encryption:

[%header%autowidth.spread,cols="a,a,a"]
|===
Property | | Description
| Client ID | `anypoint.platform.client_id` | Your Platform Client ID
| Client Secret | `anypoint.platform.client_secet` | Your Platform Client Secret
| Proxy Password | `anypoint.platform.proxy_password` | Password of the proxy configuration to connect to Platform
|===

