= Automated Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Automated policies allow API administrators to enforce compliance with organization-defined common security and logging requirements by automatically applying those "automated policies" to all APIs (specific to the ausiness-group and environment in effect when automated policies are defined. 

_Automated policies are defined on a per business-group and per-environment basis_. +
This eliminates the need for API administrators to manually apply common policies to every API as it is added; organization-mandated policies are automatically applied to the application network.

All of the xref:policies-ootb-landing-page.adoc[Mule 4 Provided Policies], and any xref:policy-mule3-custom-policies.adoc[Mule 4 Custom Policy] can be configured as automated policies.

== Support for Automated Policies

* Automated policies are only available for Mule 4 APIs hosted in a MuleSoft control plane.
* Automated policies support all runtime deployment targets (CloudHub, Runtime Fabric, and Hybrid).
* Automated policies override the same type of policy that might already be applied to a specific API. +
For example, if a Mule 4.1.2 API has an IP whitelist policy with 192.168.100.0/22 _applied at API-level_, and a new IP Whitelist _automated policy_ with 192.168.100.14/24 is applied to all supported runtime versions (4.1.1 and above), the _automated policy will prevail over the API-specific provided policy. +
Note that the IP ranges in the example above are different.
+
If an automated policy already exists (remember: specific to a given business-group and environment), that same type of policy _cannot be applied at the API-level_.


== See Also

* xref:automated-policy-apply.adoc[Applying Automated Policies]
