= Avoiding Same-Origin Restrictions
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This file is obsolete

== See Also

* xref:api-instance-landing-page.adoc[API Instance]

////

// This is a dummy page that avoids a 404.

If you cannot implement CORS for your API, another possible solution to an unreachable API is to disable the same-origin restrictions in your browser.

== Disable Same-Origin Restrictions in your Browser

Each browser handles these restrictions in a unique way and tips, tricks, and plugins are available on the internet.

Make sure you understand the potential security implications of changing browser security settings. You should only use these options for testing on your own web pages because the browser can become vulnerable to malicious scripts and other potential threats.

=== Google Chrome for Mac OS X

* Open a new Terminal window, paste the following line, and then press *Enter*: `open -a Google\ Chrome --args --disable-web-security`.

=== Google Chrome for Windows

* Open a new Command Prompt window, navigate to the location of the Chrome executable (Chrome.exe), paste the following line, and then press *Enter*: `chrome.exe --disable-web-security`.

=== Internet Explorer

Enable the option to access data sources across domains. In some versions of IE, this option is in Internet Properties > Security tab > Custom Level in Security Level for this Zone > Miscellaneous > Enable Access to Data Sources Across Domains.

////