= To Build a Mule OAuth 2 Provider
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: oauth
:meta-audience: Developer
:meta-job-phase: Implement
:meta-job:
:meta-exp-level: Expert
:meta-feature: oauth
:meta-keywords: oauth, oauth provider, authentication
:meta-synonym:
:meta-product: API Manager, Studio, Mule
:meta-applies-to: PingFederate, OpenAM

To build a provider from MuleSoft Consulting on Mule Runtime 3.8.x, perform this task.

. Set up credentials in the Mule EE Repository by creating, or by adding the credentials to, the Maven `settings.xml` file. This file is typically located in `~/.m2/settings.xml` on Linux or Mac OSX:
+
[source,xml,linenums]
----
...
  <servers>
    <server>
      <id>MuleRepository</id>
      <username>mule.username</username>
      <password>mule.password</password>
    </server>
  </servers>
...
  <profiles>
    <profile>
      <id>Mule</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>MuleRepository</id>
          <name>MuleRepository</name>
          <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
...
        </repository>
      </repositories>
    </profile>
  </profiles>
----
+
. Download the OAuthProviderStudioArchive using the link at the bottom of this topic.
. Launch Studio, and choose File > Import.
. In Select, expand Anypoint Studio and choose Anypoint Studio Generated Deployable Archive.
. Browse to the `OAuthProviderStudioArchive.zip` you downloaded, and click Finish.
. Log into your Anypoint platform account.
. Access the client ID and client secret of the account you are using to create the provider application.
. Enter your client Id and client Secret in Anypoint Studio > Preferences > Anypoint Studio > Anypoint Platform for APIs.
+
This step is necessary to test the local provider.
. In Project Explorer, right-click the project name and select Run As > Mule Application with Maven.
. In Configure Maven, enter your Maven installation home directory, and click Test Maven Configuration.
+
Assuming the test was successful, click OK; otherwise, troubleshoot the Maven problem. The console reports that the app deployed. Next, test the local provider.

== Downloads

link:{attachmentsdir}/OAuthProviderStudioArchive.zip[OAuthProviderStudioArchive]

////
Alternatively, if you use the Mule command line, start Mule as follows:
+
----
${MULE_HOME}/bin/mule -M-Danypoint.platform.client_id=client_ID -M-Danypoint.platform.client_secret=client_secret start
----
////

== See Also

* xref:to-test-local-provider.adoc[Test the provider]
* xref:external-oauth-2.0-token-validation-policy.adoc[Access Token Enforcement Using External Provider policy]
* xref:aes-oauth-faq.adoc#about-oauth-provider-models[About the External OAuth 2.0 provider]
* xref:access-management::external-identity.adoc[External Identity (setting up PingFederate and OpenAM providers)]
* xref:access-management::organization.adoc#client-id-and-client-secret[Access the client ID and client secret]