= Configuring Template Download Location for Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: policy, CloudFront

A policy template is a deployable JAR file that contains the business logic for how a policy must be implemented. Before a policy is applied to an API, the policy template is downloaded and accessed to determine the policy dependencies.

When an application with a tracked API is deployed to a runtime, it requests API Manager for the corresponding policies to be applied to the API.

The runtime to which the application is deployed must have API gateway capabilities enabled using the organization or environment credentials where the API instance is defined.

If the policy templates that are to be applied are not already available in the runtime, it requests API Manager for the URLs from where to download the templates.

By default, the legacy system is used as the download location for the templates. You can configure the runtime to download the templates from a specified source using the following system property:

`anypoint.platform.policy_template_source=<source_value>`
+
where:

[%header,cols="2*a"]
|===
|Source Value | Description
|"external" | Denotes that policy templates are to be retrieved from the legacy system. Use this default setting to maintain compatibility with previously configured firewalls.
|"internal" | Denotes that policy templates are to be retrieved from the new system. This option provides additional reliability due to internal rerouting of the requests when a server becomes unavailable.
|===

[PA: Nahuel what are we trying to say here? For 4.2.2, the URLs are provided from cloudfront? Why are we calling out only 4.2.2? What about the other versions?]
When you start Mule Runtime Engine version 4.2.2, API Manager provides the URLs for downloading the policy templates from the Mule CloudFront service, as shown in the following command line example:

[source,text,linenums]
----
./bin/mule -M-Danypoint.platform.policy_template_source=internal
----

== See Also

* xref:runtime-urls-whitelist.adoc[Ports, IPs and hostnames whitelist]
