= To Configure the Proxy Connection to an External OAuth Provider
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Mule 3.8.x, you optionally enable or disable the proxy network connection between the API and External Authentication Provider by setting the following parameter:

`external_authentication_provider_enable_proxy_setting`

This parameter is located in the following wrapper configuration file: `$MULE_HOME/conf/wrapper.conf`

Set the parameter to true or false. For example:

`wrapper.java.additional.<n>=-Danypoint.platform.external_authentication_provider_enable_proxy_settings=true`

// default changing in 3.9

By default, the parameter is false, so the proxy connection between the API and External Authentication Provider is disabled because the following proxy settings are ignored:

----
wrapper.java.additional.<n>=-Danypoint.platform.proxy_host=localhost
wrapper.java.additional.<n>=-Danypoint.platform.proxy_port=8080
----

////
In Mule 3.7.x, use the parameter in the wrapper configuration file. For example:

`anypoint.platform.ping_federate_enable_proxy_setting`

In API Gateway Runtime 2.1.x and 2.2.x, the wrapper configuration file is in `/conf/wrapper.conf`.

// default changing in 3.9

By default, the parameter is false, so the proxy connection between the API and PingFederate is disabled because the following proxy settings are ignored:
////
