= Adding an API Instance Mule Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::partial$task-create-instance.adoc[tags=intro]

== Add a New API

. Navigate to *Anypoint Platform* > *API Manager*.
. In *API Administration*, click *Add API* and select *Add new API*.
. Select *Mule Gateway*.
. Select the *Proxy type* from the following options:
+
Connect to existing application (basic endpoint):::: Use this option to directly interact with a Mule
runtime Engine (Mule) application when your application is configured with API gateway autodiscovery. See xref:api-auto-discovery-new-concept.adoc[API Autodiscovery] for more information.
+
Select the *Mule version*.
+
Deploy a proxy application:::: Use this option to interact by proxy with an application, either because
it is a Mule application not configured with API gateway autodiscovery or because it is not a Mule application.
See xref:api-proxy-landing-page.adoc[Configure Proxies for your APIs] for more information.
+
include::partial$task-configure-proxy.adoc[tags=target-type-bullet;target-type]
. Click *Next*.

include::partial$task-configure-proxy.adoc[tags=mid-steps;asset-type-options;configure-endpoint;last-steps,leveloffset=+2]


== Promote API from Environment

. Navigate to *Anypoint Platform* > *API Manager*. 
. In *API Administration*, click **Add API** and select **Promote API from environment**.
. Select the **Source Environment**.
. Select the **API** by entering the name of the API into the search field.
. Select the **API Version**.
. Select the **API instance label**.
. Optionally, uncheck any of the **Include in Promotion** options you want to exclude.
. Click **Promote**.
. Review and update the Runtime & Endpoint Configuration details as needed and click **Save**.

== Import API from Zip File

. Navigate to *Anypoint Platform* > *API Manager*.
. From *API Administration*, click **Add API** and select **Import API from zip file**.
. Click **Choose file** and select your API instance configuration zip file.
. Click **Next**.
. Review and update the API Configuration details as needed and click **Save**.

== Notes

* Although OpenAPI Specification (OAS) 3.0 is supported, the callback feature is not. To work around this issue, either handle the callback outside of the Mule runtime engine domain or use an OAS 3.0 specification that does not use callbacks.
