= Adding a Service Mesh API Instance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::partial$task-create-instance.adoc[tags=intro1;intro-service-mesh;intro2]

== Add a New API

. Navigate to *Anypoint Platform* > *API Manager*.
. In *API Administration*, click *Add API* and select *Add new API*.
. Select *Service Mesh*.
+
NOTE: After adding the API on Anypoint Platform, you need to bind it to a service using the Anypoint Service Mesh client. See xref:service-mesh::configure-service-mesh.adoc#methods-for-configuring-anypoint-service-mesh[Methods for Configuring Anypoint Service Mesh] for more information.
. Click *Next*.
+
include::partial$task-configure-proxy.adoc[tags=mid-steps;asset-type-options]
. Configure the downstream.
+
Downstream Configuration Options::::
+
include::partial$endpoint-reference-table.adoc[tags=service-mesh-downstream]
. Click *Next*.
. Configure the upstream.
+
Upstream Configuration Options::::
+
include::partial$endpoint-reference-table.adoc[tags=service-mesh-upstream]
. Click *Next*.
+
include::partial$task-configure-proxy.adoc[tags=last-steps]


// Promote API
include::partial$task-create-instance.adoc[tags=promote-api]

// Import API
include::partial$task-create-instance.adoc[tags=import-api]

== Notes

* Although OpenAPI Specification (OAS) 3.0 is supported, the callback feature is not. To work around this issue, either handle the callback outside of the Mule runtime engine domain or use an OAS 3.0 specification that does not use callbacks.
