= Adding a Mule Gateway API Instance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::partial$task-create-instance.adoc[tags=intro1;intro-mule;intro2]

== Add a New API

. Navigate to *Anypoint Platform* > *API Manager*.
. In *API Administration*, click *Add API* and select *Add new API*.
. Select and configure your runtime from the following options:
Flex Gateway:: Select Flex Gateway for any APIs that need a flexible and performant API gateway
that works with distributed and microservices environments and fits into your CI/CD environments.
+
Choose the connected Flex Gateway you have installed and registered from the list under *Select a gateway*.
+
[NOTE]
--
If you do not see a Flex Gateway listed, or you see a Flex Gateway but its status is DISCONNECTED,
See xref:gateway::flex-install.adoc[Install Flex Gateway] and xref:gateway::flex-conn-reg-run.adoc[Register and Run in Connected Mode] for more information.
--
Mule Gateway:: Select Mule Gateway if you have APIs on Mule Runtime that need an API gateway to manage, observe,
and secure your APIs.
+
Select the *Proxy type* from the following options:
+
Connect to existing application (basic endpoint):::: Use this option to directly interact with a Mule
runtime Engine (Mule) application when your application is configured with API gateway autodiscovery. See xref:api-auto-discovery-new-concept.adoc[API Autodiscovery] for more information.
+
Select the *Mule version*.
+
Deploy a proxy application:::: Use this option to interact by proxy with an application, either because
it is a Mule application not configured with API gateway autodiscovery or because it is not a Mule application.
See xref:api-proxy-landing-page.adoc[Configure Proxies for your APIs] for more information.
+
include::partial$task-configure-proxy.adoc[tags=target-type-bullet;target-type]
+
Service Mesh:: Select Service Mesh to extend Anypoint Platform API Management capabilities to your
Istio service mesh through the deployment of a Mule Adapter.
+
NOTE: After adding the API on Anypoint Platform, you need to bind it to a service using the Anypoint Service Mesh client. See xref:service-mesh::configure-service-mesh.adoc#methods-for-configuring-anypoint-service-mesh[Methods for Configuring Anypoint Service Mesh] for more information.
+
. Click *Next*.
+
include::partial$task-configure-proxy.adoc[tags=mid-steps;asset-type-options;configure-endpoint;last-steps,leveloffset=+2]


// Promote API
include::partial$task-create-instance.adoc[tags=promote-api]

// Import API
include::partial$task-create-instance.adoc[tags=import-api]

== Notes

* Although OpenAPI Specification (OAS) 3.0 is supported, the callback feature is not. To work around this issue, either handle the callback outside of the Mule runtime engine domain or use an OAS 3.0 specification that does not use callbacks.
