= Adding a Mule Gateway API Instance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:product: mule
:page-aliases: manage-exchange-api-task.adoc

include::partial$task-add-api-instance.adoc[tags=intro1;mule-intro;intro2]

[[add-api]]
== Add a New API

. Navigate to *Anypoint Platform* > *API Manager*.
. In *API Administration*, click *Add API* and select *Add new API*.
. Select *Mule Gateway*.
. Select the *Proxy type* from the following options:
+
Connect to existing application (basic endpoint):::: Use this option to directly interact with a Mule
runtime Engine (Mule) application when your application is configured with API gateway autodiscovery. See xref:api-auto-discovery-new-concept.adoc[API Autodiscovery] for more information.
+
Select the *Mule version*.
+
Deploy a proxy application:::: Use this option to interact by proxy with an application, either because
it is a Mule application not configured with API gateway autodiscovery or because it is not a Mule application.
See xref:api-proxy-landing-page.adoc[Configure Proxies for your APIs] for more information.
+
include::partial$task-add-api-instance.adoc[tags=target-type]

include::partial$task-add-api-instance.adoc[tags=mid-steps;asset-type-options]

. Configure the downstream configuration settings relevant to your proxy type:
+
.Connect to existing application (basic endpoint)
[%collapsible]
====
include::partial$api-configuration-tables.adoc[tags=mule-app-downstream]
====
+
.Deploy a proxy application
[%collapsible]
====
include::partial$api-configuration-tables.adoc[tags=mule-proxy-downstream]
====
. Click *Next*.
. Configure the upstream configuration settings relevant to your proxy type:
+
.Connect to existing application (basic endpoint)
[%collapsible]
====
include::partial$api-configuration-tables.adoc[tags=mule-app-upstream]
====
+
.Deploy a proxy application
[%collapsible]
====
include::partial$api-configuration-tables.adoc[tags=mule-proxy-upstream]
====
. Click *Next*.
+
include::partial$task-add-api-instance.adoc[tags=last-steps]

== Create New API Asset

NOTE: This feature is only available on GovCloud environments. If you want to create an API asset in other environments, refer to xref:exchange::to-create-an-asset.adoc#create-an-api-asset[]

An API asset specifies an interface completely, including its functions, descriptions, how to handle return codes, and dependencies.

Creating an asset sets the asset type, which cannot be changed. All versions of an asset always have the same type.

To create an API asset:

. In API Manager, click *Add API*.

. From the dropdown list, select *Create new API asset*

. Enter a name for the asset.

. Select the asset type from the drop-down list:

** REST API - RAML: Provide a RAML API specification file. RAML specifications must be a RAML file (.raml).

** REST API - OAS: Provide an OAS API specification file. OAS specifications can be either a YAML (.yaml) or JSON (.json) file. Exchange supports OAS 2.0 and OAS 3.0 specifications.

** SOAP API - WSDL: Provide a WSDL API specification file. SOAP specifications file can be either a WSDL (.wsdl) or XML (.xml) file.

** AsyncAPI: Provide an AsyncAPI specification file in a YAML (.yaml) or JSON (.json) file.

** AsyncAPI with Avro schemas: Provide an Avro fragment in an AVSC (.avsc) file.

** API Spec Fragment - RAML: Provide an API Fragment RAML specification file. Fragment specifications must be a RAML file (.raml).

** API Spec Fragment - JSON: Provide an API Fragment JSON specification (.json) file.

** API Spec Fragment - OpenAPI Specification (OAS): Provide an API Fragment OpenAPI specification file either JSON or YAML.

** HTTP API: This asset does not require a file. This asset type provides an API endpoint that is defined by API Manager.

. For assets that require a file:

.. Click *Choose File* to locate the API specification file.

.. Select the main file of the API. +
  If the file is a ZIP, the selected main file must be in the root directory of the ZIP file. If the file is not a ZIP or if the file is a ZIP file with only one main file, then the main file is selected automatically.

. If you want to edit the *GroupId*, *AssetId*, *Version*, and *API version* (GAV), click *Advanced*. +
Exchange generates the group ID, asset ID, and version (GAV) for you, and you can change these values as needed. You can change an API’s asset version and version separately. Use the advanced settings to change the asset version.

. Choose an option for *Lifecycle state*. The default is Stable.

. Click *Publish*.

//promote-api
include::partial$task-promote-api.adoc[]

//import-api
include::partial$task-import-api.adoc[]

== Notes

* Although OpenAPI Specification (OAS) 3.0 is supported, the callback feature is not. To work around this issue, either handle the callback outside of the Mule runtime engine domain or use an OAS 3.0 specification that does not use callbacks.
