= Adding an API Instance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you have created an API using Design Center or any other application, you can then
manage that API in API Manager by adding an API Instance.

There are three options for adding an API Instance:

* **Add a new API:** Select this option to add a completely new instance of an API.
* **Promote API from environment:** Select this option if you have an API Instance in a different environment, for instance
the sandbox environment, and you want to promote it to the current or production environment.
* **Import API from zip file:** Select this option if you have exported an API Instance from a different Anypoint Platform
instance.

When you are promoting or importing an API Instance, you will not have options to alter the configuration. However,
when you add a new API Instance, you will need to configure the endpoint as well as other settings.

== Add a New API

. Log in to Anypoint Platform.
. In the navigation bar or the Anypoint Platform page, click *API Manager*.
. Click **Add API** and select **Add new API**.
. Select and configure your runtime from the following options:
* **Flex Gateway:** Select Flex Gateway for any APIs that need a flexible, performant API gateway
that will work with distributed and microservices environments and fit into your CI/CD environments.
+
Choose the connected Flex Gateway you have installed and registered from the list under **Select a gateway**.
+
NOTE: If you do not see a Flex Gateway listed, or you see a Flex Gateway but its status is DISCONNECTED,
See xref:gateway::flex-install.adoc[Install Flex Gateway] and xref:gateway::flex-conn-reg-run.adoc[Register and Run in Connected Mode] for more information.

* **Mule Gateway:** Select Mule Gateway if you have APIs on Mule Runtime that need an API gateway to manage, observe,
and secure your APIs.
+
Select the **Proxy type** from the following options:

** **Connect to existing application (basic endpoint):** Use this option to directly interact with a Mule
runtime Engine (Mule) application when your application is configured with API gateway autodiscovery. See xref:api-auto-discovery-new-concept.adoc[API Autodiscovery] for more information.
+
Select the *Mule version*.

** **Deploy a proxy application:** Use this option to interact by proxy with an application, either because
it is a Mule application not configured with API gateway autodiscovery or because it is not a Mule application.
See xref:api-proxy-landing-page.adoc[Configure Proxies for your APIs] for more information.
+
include::partial$task-configure-proxy.adoc[tags=target-type-bullet,leveloffset=+3]

include::partial$task-configure-proxy.adoc[tags=target-type,leveloffset=+4]

include::partial$task-configure-proxy.adoc[tags=mid-steps;asset-type-options;last-steps,leveloffset=+2]

== Promote API from Environment

. Log in to Anypoint Platform.
. In the navigation bar or the Anypoint Platform page, click *API Manager*.
. Click **Add API** and select **Promote API from environment**.
. Select the **Source Environment**.
. Select the **API** by entering the name of the API into the search field.
. Select the **API Version**.
. Select the **API instance label**.
. Optionally, uncheck any of the **Include in Promotion** options you want to exclude.
. Click **Promote**.
. Review and update the Runtime & Endpoint Configuration details as needed and click **Save**.

== Import API from Zip File

. Log in to Anypoint Platform.
. In the navigation bar or the Anypoint Platform page, click *API Manager*.
. Click **Add API** and select **Import API from zip file**.
. Click **Choose file** and select your API Instance configuration zip file.
. Click **Next**.
. Review and update the API Configuration details as needed and click **Save**.

== Notes

* Although OpenAPI Specification (OAS) 3.0 is supported, the callback feature is not. To work around this issue, either handle the callback outside of the Mule runtime engine domain or use an OAS 3.0 specification that does not use callbacks.
