= Uploading a Custom Policy to Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You need to publish your custom policies to Exchange so your users can obtain and apply them to their APIs. +
API Manager lists custom policies published as assets of the Organization.

Exchange provides an API to publish or consume assets using a Maven client. You must have a unique artifact name and organization ID to publish your asset. +
See the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API] Exchange asset for more details.

== Deploying a Policy Created Using the Maven Archetype

When you create your custom policy project using the provided Maven archetypes, all the necessary plugins for uploading the policy to Exchange are already defined for you. +
See the xref:custom-policy-getting-started.adoc#setting-up-a-project-with-the-archetype[Setting up a project with the archetype] instructions for more information.

You only need to configure your Exchange credentials:

. Update the settings.xml file in your Maven .m2 directory with your Exchange credentials.
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
       <id>Repository</id>
       <username>myusername</username>
       <password>mypassword</password>
     </server>
  </servers>
</settings>
----
. Run `mvn deploy` to publish the policy to Exchange.

The custom policy is now available for you to apply to APIs that belong to the specified organization.

== Deploying a Policy Created Without Using the Maven Archetype

If you chose not to create your custom policy project using the provided Maven archetypes, you need to manually set up your Exchange deployment configurations:

. Go to your pom.xml file and define your Exchange url as a property:
+
[source,XML,linenums]
--
<properties>
  <exchange.url>https://maven.anypoint.mulesoft.com/api/v1/organizations/{OrgId}/maven</exchange.url>
</properties>
--
* Replace the {orgId} by using your organization's ID:
** Get your organization ID from *Access Management > Organization*:
*** Click the name of your organization.
*** Copy the UUID from the browser address. For example, copy _2a4b93c3-7899-4ea7-9374-f787744d8784_ from the URL.
. Additonally, in your pom.xml file, you need to define Exchange as a repository:
+
[source,XML,linenums]
--
<repository>
	<id>exchange-server</id>
	<name>MuleSoft Exchange Environment</name>
	<url>${exchange.url}</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
--
+
And also as a distribution management:
+
[source,XML,linenums]
--
<distributionManagement>
    <repository>
        <id>exchange-server</id>
        <name>Corporate Repository</name>
        <url>${exchange.url}</url>
        <layout>default</layout>
    </repository>
</distributionManagement>
--
. Finally, define your Exchange credentials in your settings.xml file in your Maven .m2 directory:
+
[source,XML,linenums]
--
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
       <id>exchange-server</id>
       <username>myusername</username>
       <password>mypassword</password>
     </server>
  </servers>
</settings>
--
+
[NOTE]
--
The IDs defined for your Exchange repositories must match.
--

== See Also

* xref:custom-policy-packaging-policy.adoc[Packaging a Custom Policy]
* xref:custom-policy-uploading-to-exchange.adoc[Uploading a Custom Policy to Exchange]
* xref:custom-policy-4-reference.adoc[Reviewing Custom Policy concepts]