= Uploading a Custom Policy to Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: custom policy, upload, Exchange

Exchange provides an API to publish or consume assets using a Maven client. You must have a unique artifact name and organization ID to publish your asset. API Manager lists custom policies published as assets of your organization.

For more information about the Exchange Maven Facade asset, see https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Exchange Maven Facade].

== Prerequisites

To upload a custom policy to Exchange, you must have the Exchange Contributors role.

== Deploying a Policy Created Using the Maven Archetype

When you create your custom policy project using the provided Maven archetype, the plugins necessary to upload the policy to Exchange are already defined for you. +
See the xref:custom-policy-getting-started.adoc#setting-up-a-project-with-the-archetype[Setting up a project with the archetype] instructions for more information.

To deploy a policy created using the Maven archetype:

. Update the settings.xml file in your Maven `.m2` directory with your Exchange credentials.
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
       <id>exchange-server</id>
       <username>myusername</username>
       <password>mypassword</password>
     </server>
  </servers>
</settings>
----
+ 
NOTE: For information on how to authenticate using a token rather than using credentials, see xref:exchange::to-publish-assets-maven#publish-and-consume-federated-assets.adoc[Publish and Consume Federated Assets].
. Run `mvn clean deploy` to publish the policy to Exchange.

The custom policy is now available for you to apply to APIs that belong to the specified organization.

== Deploying a Policy Created Without Using the Maven Archetype

If you did not create your custom policy project using the provided Maven archetype, you need to manually set up your Exchange deployment configurations.

To deploy a policy created without using the Maven archetype:

. In Anypoint Platform, find the organization ID to use as follows:
* Go to *Access Management > Organization*.
* Click the name of your organization.
* Copy the UUID from the browser address. For example, copy _2a4b93c3-7899-4ea7-9374-f787744d8784_ from the URL.
. Update your `pom.xml` file as follows: 
* Replace the `groupId` value with the organization ID from the preceding step:
[source,XML,linenums]
+
--
<groupId>{orgId}</groupId>
--
* Add the following properties and replace `{orgId}` with the organization ID from the preceding step:
+
[source,XML,linenums]
--
<properties>
  <exchange.url>https://maven.anypoint.mulesoft.com/api/v1/organizations/{OrgId}/maven</exchange.url>
  <mule.maven.plugin.version>3.2.0</mule.maven.plugin.version> <!-- check for last available version -->
</properties>
--
* Define Exchange as a repository:
+
[source,XML,linenums]
--
<repository>
	<id>exchange-server</id>
	<name>MuleSoft Exchange Environment</name>
	<url>${exchange.url}</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
--
+
* Set up your Exchange server as a distribution management:
+
[source,XML,linenums]
--
<distributionManagement>
    <repository>
        <id>exchange-server</id>
        <name>Corporate Repository</name>
        <url>${exchange.url}</url>
        <layout>default</layout>
    </repository>
</distributionManagement>
--
* Add the following build plugins:
** Mule Maven plugin: Verifies that all necessary files are present and that all requirements are met to correctly package the policy.
** Maven Deploy plugin: Communicates with the Exchange repository and uploads the policy JAR and YAML files.
+
[source,XML,linenums]
--
<build>
    <plugins>
        <plugin>
            <groupId>org.mule.tools.maven</groupId>
            <artifactId>mule-maven-plugin</artifactId>
            <version>${mule.maven.plugin.version}</version>
            <extensions>true</extensions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-deploy-plugin</artifactId>
            <executions>
                <execution>
                    <id>upload-template</id>
                    <phase>deploy</phase>
                    <goals>
                        <goal>deploy-file</goal>
                    </goals>
                    <configuration>
                        <repositoryId>exchange-server</repositoryId>
                        <url>${exchange.url}</url>
                        <file>${project.basedir}/${project.artifactId}.yaml</file>
                        <generatePom>false</generatePom>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>${project.version}</version>
                        <packaging>yaml</packaging>
                        <classifier>policy-definition</classifier>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
--
* Add the following plugin repository:
+
[source,XML,linenums]
--
<pluginRepositories>
    <pluginRepository>
        <id>mule-plugin</id>
        <name>Mule Repository</name>
        <url>https://repository.mulesoft.org/nexus/content/repositories/public/</url>
    </pluginRepository>
</pluginRepositories>
--
. Set up your Exchange credentials in the `settings.xml` file in your Maven `.m2` directory:
+
[source,XML,linenums]
--
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
       <id>exchange-server</id>
       <username>myusername</username>
       <password>mypassword</password>
     </server>
  </servers>
</settings>
--
+ 
NOTE: For information on how to authenticate using a token rather than using credentials, see xref:exchange::to-publish-assets-maven#publish-and-consume-federated-assets.adoc[Publish and Consume Federated Assets].

. Deploy the policy using the `mvn clean deploy` command.
+
[NOTE]
--
The IDs defined for your Exchange repositories must match.
--

== See Also

* xref:custom-policy-packaging-policy.adoc[Packaging a Custom Policy]
* xref:custom-policy-4-reference.adoc[Reviewing Custom Policy Concepts]
