= Event Authentication Extension
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Event Authentication Extension for Mule 4 allows policies to easily update the authentication data of
the xref:about-mule-event.adoc[Mule event], in order to be able to propagate information through the flow pipeline.
A common use case for this is applying a xref:external-oauth-2.0-token-validation-policy.adoc[OAuth policy] along with
a xref:rate-limiting-and-throttling-sla-based-policies.adoc[Rate Limiting SLA Based policy], in which the first policy
validates a token provided in the request and (if it is a valid token) it retrieves the client ID from the provider,
and saves it in the Event’s authentication object. Later, this will be used by the Rate Limiting policy to verify that 
the client application corresponding to that client credentials has not reach its quota limit.

== Namespace

[source,xml,linenums]
----
<mule
xmlns:authentication="http://www.mulesoft.org/schema/mule/authentication"

xsi:schemaLocation="
http://www.mulesoft.org/schema/mule/authentication http://www.mulesoft.org/schema/mule/authentication/current/mule-authentication.xsd">
----

== Operations

- Set authentication

- Add properties

=== Set Authentication

This operation sets new authentication information to the Mule event, overriding the existing one, if present.

==== Parameters

* `principal` (Optional)
+
A string generally used to store the identity of a subject in an authentication process. For example, a username or a client ID attribute.
If not specified, it is stored with null value.
+
* `credentials` (Optional)
+
A string generally used to store the verification data of a subject in an authentication process. For example, a password or a client secret attribute.
If not specified, it defaults to an empty string.
+
* `properties` (Optional)
+
A DataWeave 2.0 expression that resolves to a Map of properties to be set to the authentication object.
+
*Example*
+
[source,xml,linenums]
----
<authentication:set-authentication principal="Principal" credentials="Skinner"
                                 properties="#[
                                           'FirstProperty': 'FirstPropertyValue',
                                           'SecondProperty': 'SecondPropertyValue'
                                 ]"/>
----


=== Add Properties

This operation adds (or overrides, if there are existent matches) properties to the current authentication object of the Mule Event.
If the authentication object does not exist, it creates a new one with the specified properties, empty credentials and null principal.

==== Parameters

* `newProperties` (Optional)
+
A DataWeave 2.0 expression that resolves to a Map of properties to be added to the authentication object. If not specified, it does nothing.
+
*Example*
+
[source,xml,linenums]
----
<authentication:add-properties newProperties="#[

                                           'FirstProperty': 'FirstPropertyValue',
                                           'SecondProperty': 'SecondPropertyValue'

                                 ]"/>
----
