= Getting Started with Managing an API 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use API Manager to apply policies and to add contracts, alerts, and SLA tiers to your API Instance. Additionally, you can configure a runtime for your API that runs in CloudHub. Although you can also deploy your API runtime using Mule runtime engine (Mule) and Hybrid, deploying your API proxy directly to CloudHub is the fastest and easiest.

NOTE: If you are running an API with a standalone server, use the xref:manage-exchange-api-task.adoc[classic API creation flows]
to manage your API.

You can manage your API using the following steps:

. xref:exchange::to-create-an-asset.adoc#create-an-api-asset[Create an API asset in Exchange]
+
You can create an REST, HTTP, or SOAP API asset in Exchange and manage it as an API Instance
in API Manager.
. xref:create-instance-task.adoc[Add an API Instance in API Manager]
+
An API Instance is a proxy of an API that serves the upstream. API instances support the application of policies
and can be deployed to an API gateway. 
. xref:policies::policies-included-apply.adoc[Apply a Policy in API Manager]
+
A policy extends the functionality of an API and enforces certain capabilities such as security. A policy
can control access and traffic. For example, a policy can generally control authentication, access,
allotted consumption, and service level access (SLA).

== See Also

* xref:defining-sla-tiers.adoc[Learn about SLA Tiers]
* xref:api-contracts-landing-page.adoc[Learn about granting access to an API]
* xref:api-proxy-landing-page.adoc[More on API proxies]
