= Governing API Instances
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


API Manager is closely integrated with xref:api-governance::index.adoc[API Governance] to govern aspects of API instances with governance rulesets. Applying a governance ruleset to your API ensures that every instance of that API conforms to standards such as what policies are applied and if a TLS context is required. 

NOTE: Only REST APIs support instance governance. 

To govern an API instances:

. <<apply>>
. <<view>>
. <<fix>>

[[apply]]
== Apply a Governance Rulesets

To govern API instances, you must apply a governance ruleset to your desired API.

To apply a governance ruleset, see xref:api-governance::create-profiles[].

Additionally, you can create custom rulesets to satisfy your specific needs. 

To create custom governance rulesets, see xref:api-governance::create-custom-rulesets[].

[[view]]
== View Instance Conformance Status


[[fix]]
== Fix Conformance Issues

To fix issues in you API instances, see xref:api-governance::fix-instance-conformance-issues.adoc[].

== See Also

* xref:using-api-alerts.adoc[Review Alerts Concepts]
* xref:gateway::flex-use-api-alerts.adoc[Add API Alerts for Flex Gateway]
