= Governing API Instances
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


API Manager is closely integrated with xref:api-governance::index.adoc[Anypoint API Governance] to govern aspects of API instances with governance rulesets. Applying a governance ruleset to your API ensures that every instance of that API conforms to standards such as what policies are applied and if a TLS context is required.  

To govern an API instance:

. <<apply-a-ruleset>>
. <<view-api-governance>>

[[apply-a-ruleset]]
== Apply a Governance Ruleset

To govern API instances, you must apply a governance ruleset to your desired API. To apply a governance ruleset, see xref:api-governance::create-profiles.adoc[].

To create custom rulesets that enforce your own API management standards, see xref:api-governance::create-custom-rulesets.adoc[].

[[view-api-manager]]

== View and Fix Instance Conformance issues in API Manager

To view the conformance status of an API instance:

. Navigate to *Anypoint Platform* > *API Manager*. 
. Click the name of the API instance for which you want to view the conformance status.
+
*Instance Conformance* appears in the *API Summary* pane.
. If the instance is not conformant, select the *Governance Report* page to view nonconformance details for each ruleset.
. Click *View details* for each ruleset for more information about the conformance issues.


== See Also

* xref:api-governance::fix-instance-conformance-issues.adoc[]
