= HTTP Policy Transform Extension
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

NOTE: Valid for versions 3.0.0 and up

In Mule 4.1.0 and later, the HTTP Policy Transform Extension is available to use in policies. This extension simplifies the modification of HTTP requests and responses that go
 through the different policies.

== Namespace

[source,xml,linenums]
----
<mule
xmlns:http-transform="http://www.mulesoft.org/schema/mule/http-policy-transform"

xsi:schemaLocation="
http://www.mulesoft.org/schema/mule/http-policy-transform http://www.mulesoft.org/schema/mule/http-policy-transform/current/mule-http-policy-transform.xsd">
----

== Operations

- Add Headers Operations
  * Add Request Headers
  * Add Response Headers

- Remove Headers

- Set Response

- Set Request


=== Add Headers Operations

The way this operations work depends on its correlation with the Mule message:

* Correlated: adds headers in requests and responses of the HTTP Listener and Requester.
* Not correlated: creates a new request / response with the specified headers.

For example, the operation and Mule message are not correlated if the specified outputType is `response`, but the Mule Message contains the HTTP Request. When the operation executes, it overwrites the entire value, creating a new response with the specified headers.  If the Mule Message contains a HTTP response, it just adds the headers to the request.

==== Add Request Headers

This operation is used to inject headers on the request. It should be called in the following contexts:

* From Source Policy, before the `execute-next` is invoked.
* From Operation Policy, before the `execute-next` is invoked.

===== Parameters

* `headers`
+
A DataWeave expression that resolves to the Map of headers to be added to present message attributes
+
*Example*
+
[source,xml,linenums]
----
<http-transform:add-request-headers outputType="response">
<http-transform:headers>#[
{
  'FirstHeader': 'FirstHeaderValue',
  'SecondHeader': 'SecondHeaderValue',
  'ThirdHeader': 'ThirdHeaderValue'
}
]</http-transform:headers>
</http-transform:add-request-headers>
----

==== Add Response Headers

This operation is used to inject headers on the response. It should be called in the following contexts:

* From Source Policy, after the `execute-next` is invoked.
* From Operation Policy, after the `execute-next` is invoked.

===== Parameters

* `headers`
+
A DataWeave expression that resolves to the Map of headers to be added to present message attributes
+
*Example*
+
[source,xml,linenums]
----
<http-transform:add-response-headers>
<http-transform:headers>#[
{
  'FirstHeader': 'FirstHeaderValue',
  'SecondHeader': 'SecondHeaderValue',
  'ThirdHeader': 'ThirdHeaderValue'
}
]</http-transform:headers>
</http-transform:add-response-headers>
----


=== Remove Headers

This operation removes headers from both requests and responses of the HTTP Listener and Requester. Returned attributes are always of the same type as the input attributes. This operation is case-insensitive.

==== Parameters

* `header-names`
+
A Data-Weave expression that resolves to an Array of header names to be removed.
+
*Example*
+
[source,xml,linenums]
----
<http-transform:remove-headers>
    <http-transform:header-names>#[['FirstHeader', 'SecondHeader']]</http-transform:header-names>
</http-transform:remove-headers>
----

=== Set Response

This operation sets a complete HTTP response. You use this operation when the
policy prevents the flow from being executed; thus, there is no HTTP response in place.

==== Parameters

* `statusCode`: An integer representing the HTTP status code of the response.

* `reasonPhrase`: A string representing the HTTP reason phrase of the response.

* `body`: The content of the HTTP response.

* headers: A DataWeave expression that resolves to the map of headers of the HTTP response
+
*Example*
+
[source,xml,linenums]
----
<http-transform:set-response statusCode="203" reasonPhrase="policyReasonPhrase">
    <http-transform:body>#['policyPayload']</http-transform:body>
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
</http-transform:set-response>
----

=== Set Request

This operation sets a complete HTTP request that the HTTP Requester executes.

==== Parameters

* `requestPath`: The path where the HTTP Request is being sent.

* `body`: The content of the HTTP Request.

* `headers`: A DataWeave expression that resolves to the map of headers of the HTTP request.

* `uriParams`: A DataWeave expression that resolves to the map of URI params of the HTTP request.

* `queryParams`: A DataWeave expression that resolves to the map of query params of the HTTP request.
+
*Example*
+
[source,xml,linenums]
----
<http-transform:set-requester-request requestPath="/backend/policy/{policyUriParam}">
    <http-transform:body>#['policyPayload']</http-transform:body>
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
    <http-transform:uri-params>#[
        {
            'FirstUriParam': 'FirstUriParamValue',
            'SecondUriParam': 'SecondUriParamValue'
        }
    ]</http-transform:uri-params>
    <http-transform:query-params>#[
        {
            'FirstQueryParam': 'FirstQueryParamValue',
            'SecondQueryParam': 'SecondQueryParamValue'
        }
    ]</http-transform:query-params>
</http-transform:set-requester-request>
----

== Upgrading to version 3.0.0 and above

NOTE: The following instructions were not needed for previous versions of the extension. For users moving to a later version, this is advised.

When a policy using the HTTP Policy Transform Extension is packaged, the xref:http-connector.adoc[Mule HTTP Connector] is unnecessarily added to the policy JAR file.

To avoid this, in the policy's POM file we should add the corresponding exclusion in the extension's dependency declaration. This is:

[source,xml,linenums]
----
  <dependency>
      <groupId>com.mulesoft.anypoint</groupId>
      <artifactId>mule-http-policy-transform-extension</artifactId>
      <version>${httpPolicyTransformVersion}</version>
      <classifier>mule-plugin</classifier>
      <exclusions>
          <exclusion>
              <groupId>org.mule.connectors</groupId>
              <artifactId>mule-http-connector</artifactId>
          </exclusion>
      </exclusions>
  </dependency>
----
