= IP Allowlist
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: IP, allowlist, validation, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | IP Allowlist
>s|Summary      | Allows a list or range of specified IP addresses to request access   
>s|Category | Security
>s|First Mule version available | v4.1.0
.1+>.^s| Returned Status Codes
| 403 - IP is rejected
|===


The IP Allowlist policy allows a list or a range of specified IP addresses access to a protected resource when a match is found between a source IP (specified when configuring the policy) and a list of individual IPs or range of IPs.

Based on your business need, specify either a DataWeave 2.0 expression for Mule runtime engine 4 (Mule) or a MEL expression for Mule 3. These expressions define the source IP used by the policy to determine whether the IP belongs to the policy's restricted IP list.


[[specifying_ip_address]]
== Specifying IP Addresses to Allowlist in Your Policy 

Specify IP addresses to allow access to your policy based on:

* The IP address of the request
* The origin IP address that is determined by resolving a specific DataWeave or MEL expression, such as the https://en.wikipedia.org/wiki/X-Forwarded-For[x-Forwarded-For] header
* Any other origin.

=== Allowlisting Access Based on the IP address of the Request

Allowlist access based on the IP address of the request in any of the following ways:

* Define a specific IP address by enumerating it in the Allowlist field, for example, `192.168.1.1`.
* Define a subset of addresses by identifying a subnet mask, for example, `192.168.3.1/30`, which includes the consolidated range `192.168.3.01` through `192.168.3.3`.
* Define a whole range of IP addresses by stating the relevant octets of the IP address you want to permit, for example, setting `192.168`, which includes IP addresses from `192.168.0.0` through `192.168.255.255`.


=== Allowlisting Access Based on the Origin IP Address of the x-Forwarded-For Header

If the client connects to your API through an HTTP proxy or a load balancer, you can allowlist the client's specific IP address (the IP address originating the request) instead of the address that appears in the request.

For example, if you want to allowlist `192.168.2.3`(private IP) and the address of a client connecting through an HTTP proxy is `92.40.1.255` (public IP), the client requests appear with the public address using the proxy.

Typically, applications use the `X-Forwarded-For` header to identify the origin IP addresses of a request that was redirected to your endpoint.

You can use a DataWeave 2.0 or MEL expression in the policy to instruct the service to look for the IP address in the `x-Forwarded-For` header. 

When you insert the IP address in the IP expression field of the policy parameters, Anypoint Platform is instructed to look for the starting IP address in the concatenated values of the `x-Forwarded-For` header of the request:

[source,mel]
----
#[attributes.headers['x-forwarded-for']]
----

== Configuring Policy Parameters

When you apply the IP Allowlist policy to your API from the UI, configure the following parameters:

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description 
|IP expression  |The DataWeave 2.0 or MEL expression to be used for extracting the IP address from this API request. 
|Allowlist |The list of IP addresses allowed access to the API. You can define one IP or IP range at a time, as many times as required.  For more information, see <<specifying_ip_address,Specifying IP Addresses to Allowlist in Your Policy>>.
|Method & Resource conditions |The option to add configurations either to a select few or to all methods and resources of the API.
|===
