= IP Whitelist
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: IP, whitelist, validation, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | IP Whitelist
>s|Summary      | Allows access to request from a list or range of specified IP addresses
>s|Category | Security
>s|First Mule version available | 3.8.0
.1+>.^s| Returned Status Codes
| 403 - IP is rejected
|===


The IP Whitelist policy allows a list or range of IP addresses to access a configured API endpoint.


== How This Policy Works

//Nahuel anything to add here?

[[specifying_ip_address]]
== Specifying IP Addresses to Whitelist in Your Policy 

You can specify the IP addresses to whitelist in the policy using the following ways:

* Access based on the IP address of the request
* Access based on the origin IP address of the x-Forwarded-For header

=== Whitelisting Access Based on the IP address of the Request

To blacklist access based on the IP address of the request, you can:

* Define a specific IP address by enumerating it in the white space, for example, `192.168.1.1`.
* Define a subset of addresses by identifying a subnet mask. 
For example, `192.168.3.1/30`, which includes the consolidated range: `192.168.3.0 - 192.168.3.3`.
* Define a whole range of IP addresses by stating the relevant octets of the IP address you want to permit. 
+
For example, setting `192.168` will include IP addresses from `192.168.0.0` to `192.168.255.255`.

=== Whitelisting Access Based on the Origin IP Address of the x-Forwarded-For Header

If the client connects to your API through an HTTP proxy or a load-balancer, you can blacklist the client's specific IP (the IP originating the request) instead of the address that appears in the request.

For example, suppose you want to blacklist `192.168.2.3` and the address of a client connecting through an HTTP proxy is `92.40.1.255`, the client requests appear with this public address.
//Nahuel, we need to improve the previous para.

As a workaround, use the `X-Forwarded-For` header to identify the origin IP addresses of a request that was redirected to your endpoint.

//nahuel in IP Blacklist, this para mentioned that uses typically use the header. Here we mention it as a workaround. Which one is accurate?

You can use a Mule expression in the policy to instruct the service to look for the IP address in the 'x-Forwarded-For' header. 

When you insert the IP address in the IP expression field of the policy parameters, the API Platform is instructed to look for the originating IP address that ranks in the concatenated values of the `x-Forwarded-For` header of the request:
+
[source,mel]
----
#[attributes.headers['x-forwarded-for']]
----

== Configuring Policy Parameters

When you apply the IP Whitelist policy to your API from the UI, you can configure the following parameters:

[%header%autowidth.spread,cols="a,a,a"]
|===
| Parameter | Description 
|IP expression  
|The Mule expression to be used for extracting the IP address from this API request. 
|Blacklist
|The list of IP addresses that must be granted access to the API. Add one or several IP addresses separated by a comma, or define a range. For more information, see <<specifying_ip_address,Specifying IP Addresses to Whitelist in Your Policy >>.
|Method & Resource conditions
|The option to add configurations to only a select few or all methods and resources of the API.
|===