= Reviewing JSON and XML Threat Protection Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: XML, policy, validation

This file is obsolete

== See Also

***** xref:apply-configure-json-threat-task.adoc[JSON Threat Protection]
***** xref:apply-configure-xml-threat-task.adoc[XML Threat Protection]

////

JSON and XML are prone to the same types of malicious injections, often characterized by unusual inflation of elements and nesting levels. Attackers use recursive techniques to consume memory resources. Dramatic swings in the size of the application data often signal a security problem. The JSON and XML threat protection policies help protect your applications from such intrusions.

In the event Mule Runtime fails to detect an attack, you need to monitor and design your services architecture with layers of protection in addition to these policies.

Configure and apply the JSON and XML threat protection policies using the procedures in subtopics listed below.

== Responses to JSON and XML Threat Protection Policies

Reponses to these policies are:

* 200
+
Message successfully sent.
+
* 400 Bad Request
+
Any request that violates the configured limits causes a Bad Request error.

////