= Managing API Instance Versions
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Anypoint Exchange (Exchange), you can add, delete, and deprecate API versions, also known as _Exchange assets_. An API version in Exchange can have its own RAML file, API portal, and URL. For more information on how to manage API versions in Exchange, see xref:exchange::manage-versions.adoc[Manage Versions].

After you publish new version details for an API definition to Exchange, you must change the version of your API Instance in API Manager if you want the instance to reflect the latest version. For more information on API Instances, see xref:api-instance-landing-page.adoc[API Instance].

To change the asset version of an API Instance:

. Go to *Anypoint Platform* > *API Manager*.
. In *API Administration*, click the name of the API whose version you want to manage.
. Select *Actions* > *Change API specification*.
. In *Asset version*, Select *latest*. 
. Click *Change*.

== See Also

* xref:api-instance-landing-page.adoc[API Instance]
* xref:environment-permission-task.adoc[Granting Permission to Access an environment]
* xref:exchange::index.adoc[Anypoint Exchange documentation]
* xref:exchange::to-create-an-asset.adoc[Create an Asset in Exchange]
* xref:exchange::to-delete-asset.adoc[Delete an Asset in Exchange] (also describes deprecating an asset)
* xref:exchange::about-portals.adoc[About Exchange Portals]
