= Managing API Versions
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create an API in Anypoint Platform, you configure the version details for the API and then publish it to Anypoint Exchange (Exchange). The API version resides in Exchange, and not in API Manager. However, you then manage this API version from API Manager.

After setting up an API version for management, you repeat the process to create another instance. Attempting to configure the same version creates another instance of the version. You can create multiple instances and expand the version information to view details about them.

You can add, delete, and deprecate API versions, also known as _Exchange assets_, in Exchange. An API version in Exchange can have its own RAML file, API portal, and URL. See xref:exchange:manage-versions.adoc[Manage Versions] for more information.

== See Also

* xref:api-instance-landing-page.adoc[API Instance]
* xref:environment-permission-task.adoc[Granting Permission to Access an environment]
* xref:exchange::index.adoc[Anypoint Exchange documentation]
* xref:exchange::to-create-an-asset.adoc[Create an Asset in Exchange]
* xref:exchange::to-delete-asset.adoc[Delete an Asset in Exchange] (also describes deprecating an asset)
* xref:exchange::about-portals.adoc[About Exchange Portals]
