
= Creating Client Applications with Connected Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: grant access, api, contracts


For automation use cases, you can use Connected Apps to create and manage client applications.

Connected Apps help user delegate their access without sharing sensitive credentials or giving full control of their applications to third parties. Actions taken by connected apps are audited, and users can revoke access at any time.


== Creating a Connected App

To create a Connected App, see xref:access-management::connected-apps-developers.adoc[].

When you create the Connected App to manage client applications, ensure that you:

. Select *App acts on its own behalf (client credentials)* for *Type*.
. Add the *Application Creator* scope.

The new Connected App can now create client applications and manage the client applications that it creates.


== Client Application Management

When a Connected App creates a client application, the owner of the Connected App is the owner of the new client application.   

The Connected App can manage the client application it created, and can perform the following actions:

* Add users as client application owners
* Request access to an API instance
* Request a tier change
* Reset a client applications secret

You cannot add a Connect App as an owner of a client application. Connected Apps can only manage the client applications they create.


== See Also

* xref:exchange::to-request-access.adoc[Request Access to API Instances from Exchange]
* xref:remove-client-app-latest-task.adoc[Remove API Instance Contracts]
* xref:access-client-app-id-task.adoc[Obtain Client ID and Client Secret Credentials of a Client Application]