
= Approve or Reject Access Requests 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: grant access, api, contracts

After users xref:exchange::to-request-access.adoc[request access] to your API instance from Anypoint Exchange, you can manually approve or reject requests from API Manager. 

== Task Prerequisite

To manually approve or reject requests, you must have:

* Configured the SLA tier for the application 
* The Organization Administrator, API Manager Environment Administrator, or the Manage Contracts permission

== Manually Approve Requests

To approve or reject requests to access your API:

. In API Manager, click *API Administration*.
. Click the name of the API instance to which you are requesting access. 
. From the configuration page for the API instance, click *Contracts* from the left menu. 
+
The request appears.
. Click either *Approve* or *Reject* to approve or reject the access request, respectively.


== See Also

* xref:exchange::to-request-access.adoc[Request Access to API Instances from Exchange]
* xref:remove-client-app-latest-task.adoc[Remove API Instance Contracts]
* xref:access-client-app-id-task.adoc[Obtain Client ID and Client Secret Credentials of a Client Application]