= OAuth 2 Policies concepts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To secure an API in Anypoint Platform using OAuth 2.0, you can use the following policies and the matching OAuth 2.0 provider:

* One of the following policies available in federated organizations, are configured with specific OAuth 2.0 providers:
** OpenAM OAuth Token Enforcement policy
** PingFederate OAuth Token Enforcement policy
** OpenID Connect Access Token Enforcement Policy
* Available in all organizations:
** xref:external-oauth-2.0-token-validation-policy.adoc[Mule OAuth 2.0 Access Token Enforcement policy] and xref:mule-oauth-provider-landing-page.adoc[Mule OAuth 2.0 Provider].

None of these token enforcement policies allow access to the OAuth 2.0 protected resources if credentials from non-Mule client applications are used.

An OAuth 2.0 Authorization Enforcement policy, which you can apply to an API in Anypoint Platform, connects to an OpenAM authorization server, an OpenID Connect Token Introspection endpoint, PingFederate authorization server, or a Mule OAuth 2.0 provider.

*Important:* The xref:external-oauth-2.0-token-validation-policy.adoc[Mule OAuth 2.0 Access Token Enforcement policy] is designed to work exclusively with a Mule OAuth 2.0 provider. Using the policy with any other OAuth 2.0 provider (for example, Facebook, Google, or Azure) is not supported.

== Prerequisites

To apply OAuth 2.0 policies, you must:

* Have an Anypoint Platform organization administrator role or have permission to create or manage APIs in your environment.
* Configure your Anypoint Platform organization as a federated organization using either OpenAM, OpenID Connect, or PingFederate. 
+
Alternatively, have a xref:mule-oauth-provider-landing-page.adoc[Mule OAuth 2.0 Provider] configured and running.

== See Also

* xref:mule-oauth-provider-landing-page.adoc[Mule OAuth 2.0 Provider]
* xref:access-management::managing-api-clients.adoc[Setting up OpenAM, PingFederate, or OpenID Connect]
* xref:client-id-based-policies.adoc[Reviewing Client ID-Based Policies concepts]
* xref:oauth-policy-implementation-concept.adoc[Reviewing OAuth 2 Policy Implementation]
