= Mule OAuth 2.0 Provider Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To run the Mule OAuth Provider in conjunction with the OAuth 2.0 Access Token Enforcement Using External Provider policy, you have to deploy the OAuth provider to a runtime with API Gateway capabilities (either Mule runtime engine v3.8.0 or later, or API Gateway v2.x.x) with the corresponding organization credentials correctly specified.


== Configuring Endpoint Paths

The Provider has three main endpoint paths that should be defined.

Default paths:

* `/validate`
+
Verifies the validity of the token.
+
NOTE: Yo may define more than one validation endpoint, each of them enforcing different scopes, for example. See <<Configuring Scopes>> for more info about this.
+
* `/authorize`
+
Provides a one-time-use code to be exchanged by an actual token when calling /access_token.
+
* `/access_token`
+
Returns an OAuth 2.0 token.

== Configuring Scopes

OAuth 2.0 https://tools.ietf.org/html/rfc6749#page-23[scopes] are a way to further limit access to a resource protected by OAuth. You may define words like READ, WRITE, or some other words that makes sense in the context of your organization (eg. CONTRACTOR, PUBLIC, EMPLOYEES_ONLY, etc).

You can define scopes in three different places.

First, the universal set (ie "defaultScopes"), where you define all possible scopes.

Then, you may configure the validation endpoint (eg /validate) to enforce a particular subset of the the scopes defined in the previous step.

You may also enforce scopes by specifying a space separated list in the policy itself.

== Integrating concepts with an example

[source,xml,linenums]
----
...
    <oauth2-provider:config name="external-oauth2-provider"
    							resourceOwnerSecurityProvider="resourceOwnerSecurityProvider"
    							clientSecurityProvider="clientSecurityProvider"
    							supportedGrantTypes="AUTHORIZATION_CODE,IMPLICIT,RESOURCE_OWNER_PASSWORD_CREDENTIALS,CLIENT_CREDENTIALS"
    							listenerConfig="https.listener"
    							scopes="CONTRACTOR, PUBLIC_READ, EMPLOYEES_ONLY, WRITE"
                                defaultScopes="CONTRACTOR, PUBLIC_READ, EMPLOYEES_ONLY, WRITE"
                                clientStore="clientObjectStore">
    		<oauth2-provider:token-config path="/access-token" tokenTtl="5" tokenTtlTimeUnit="SECONDS" tokenStore="tokenObjectStore">
                <oauth2-provider:refresh-token-strategy>
                    <oauth2-provider:single-refresh-token objectStore="refreshTokenObjectStore"/>
                </oauth2-provider:refresh-token-strategy>
            </oauth2-provider:token-config>
    		<oauth2-provider:authorization-config path="/authorize" authorizationCodeStore="authorizationCodeObjectStore"/>
    	</oauth2-provider:config>

        <flow name="validateToken">
            <http:listener path="/validate" config-ref="https.listener"/>
            <oauth2-provider:validate-token scopes="#[['PUBLIC_READ']]" config-ref="external-oauth2-provider" accessToken="#[attributes.queryParams.access_token]"/>
            <error-handler>
                <on-error-continue type="OAUTH2-PROVIDER:TOKEN_UNAUTHORIZED">
                    <set-payload value="UNAUTHORIZED_TOKEN"/>
                </on-error-continue>
            </error-handler>
        </flow>
...
----