= Policy Types
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: policy, custom, ootb, offline

Policies are available in differnt options, such as, Default, Custom, and Automated. Each type of the policy differs by its scope, management, and usability.

== Default Policies

Mulesoft provides several policies that are ready-to-use and cover different areas, such as authentication, security management, threat protection, and tokenization. You can apply any of these policies using the UI to any of your API endpoints. After you apply a policy, it is managed by the API Manager for its complete lifecycle. You can apply a Default policy to a spcific API. To apply a policy globally to all APIs, you must automate the policy.

[PA]: DO we release new versions of an existing policy? How does it affect a customer that already has a version applied? What do they have to do with it.

== Automated Policies

Automated Policies are applied globally across all APIs. You can globally apply a Default or a Custom policy. However, you require specific roles and permissions to apply Automated policies.

== Custom Policies

Even though Mulesoft provides a wide range of Default policies to suit your business needs, you might have a scenario that may not be covered by a Default policy. In such cases, you can create a Custom policy. You can extend an exiting functionality, or define new ones with a Custom policy. These policies come in two different flavors, namely: Offline and Online.

=== Online Custom Policies
Online Custom policies are applied and managed by the API Manager.
[PA Need more pertinent information here.]


=== Offline Custom Policies
Offline Custom policies are applied directly to the runtime. You do need to apply them using the API Manager. 
[PA Need more pertinent information here.]

== See Also

* xref:policies-mule3.adoc[Policies in Mule 3]
* xref:policies-mule4.adoc[Policies in Mule 4]