= PingFederate OAuth 2.0 Token Enforcement
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[width="100%", cols="5,15"]
|===
>s| Policy Name | PingFederate OAuth 2.0 Token Enforcement
>s|Summary      | Allows access only to authorized client applications
>s|Category | Security
>s| Since Mule Version | 3.8.0
.4+>.^s| Returned Status Codes
|400 - Invalid token
|401 - Unauthorized or Connection error when connecting to the authorization server
|403 - Forbidden, invalid client application credentials
|500 - Bad response from authorization server, or WSDL SOAP Fault error.
|===

IMPORTANT: This policy is only available in a Federated organization configured to use PingFederate as Client Management solution.

The PingFederate OAuth 2.0 Token Enforcement Policy restricts access to a protected resource, by only allowing HTTP requests if the token provided in such request is a valid one and, optionally, the required OAuth scopes are fulfilled.
The policy validates the token, by connecting to a PingFederate authorization server. The token is obtained specifying the credentials of an xref:api-contracts-landing-page.adoc[authorized client application] when performing the xref:oauth-dance-about.adoc[OAuth dance].

Before applying this policy, make sure that you are familiar with its xref:about-configure-api-for-oauth.adoc[prerequisites]

When you apply the policy, you may optionally define a space separated list of https://tools.ietf.org/html/rfc6749#page-23[OAuth 2.0 scopes] to be enforced by it.
OAuth 2.0 scopes are a way to further limit access to a resource protected by OAuth. You may define words like READ, WRITE, or some others that make sense in the context of your organization (eg. CONTRACTOR, PUBLIC, EMPLOYEES_ONLY, etc).

== Supported Grant Types

A client application created on a PingFederate Federated organization allows any combination of xref:oauth-grant-types-about.adoc[OAuth grant types]: Implicit, Client Credentials, Resource Owner Password Credentials, and Authorization Code.
On PingFederate side, you can enable or disable any combination of grant types. For the OAuth dance to be successful, the grant type to be used should be enabled in both, PingFederate and client application.

== Performance

To improve performance, once a token is validated, by default, the token is cached by the system until it expires. Sometimes it is desirable to reduce or even disable the caching mechanism, for example to take into account revoked token scenarios.

To control token cached time (ie token cache time before retrying validation against the OAuth Provider), you may specify the following property:

[listing]
anypoint.platform.max_federation_expiration_time=<a number equal or greater than 0>

== Communicating to the OAuth provider through a proxy

To enable the PingFederate OAuth 2.0 Token Enforcement Policy to use the Gateway proxy settings, specify the following property:

[listing]
anypoint.platform.external_authentication_provider_enable_proxy_settings=<true|false(default)>

Setting the previous property to true makes the policy use the runtime proxy settings if specified. For example:

----
anypoint.platform.proxy_host=localhost
anypoint.platform.proxy_port=8080
----

== Leveraging OAuth provider information

When a token is successfully validated by the OAuth provider, the provider sends back to the policy who requested the token validation, some extra information, including fields that are PingFederate side configurable.

Token validation response example from the authorization server:

[source,text,linenums]
----
{
    "uid":"john.doe",
    "mail":"john.doe@example.com",
    "scope":["uid","mail","cn","givenName"],
    "grant_type":"password",
    "cn":"John Doe",
    "realm":"/",
    "token_type":"Bearer",
    "expires_in":3600,
    "givenName":"John",
    "access_token":"fa017a0e-1bd5-214c-b19d-03efe9f9847e"
}
----

The fields returned by the OAuth provider are processed by the policy, and:

- For each field, the original request to the protected resource is enriched with HTTP headers in the form: `X-AGW-` + key=value
* [Mule 4] As part of the policy configuration, you may choose to not Expose Headers. In that case, the request will *not* be enriched with `X-AGW` headers.
- For further processing within the flow, the original unparsed response from the provider is made available for further processing.
* [Mule 3] A flow variable `['_agwUser']` is setup. To access a particular value in the map, specify it directly using a MEL expression. For example:
[listing]
#[flowVars['_agwUser']['mail']]

* [Mule 4] The information is stored in an `authentication` object. Supposing that a "mail" field is returned, its value can be accessed using the following DataWeave 2.0 expression:
[listing]
#[authentication.properties.userProperties.mail]

TIP: You can use the extra information to further tune your business logic.

== See Also

* xref:api-contracts-landing-page.adoc[Client Applications and Contracts]
* xref:about-configure-api-for-oauth.adoc[OAuth 2.0 Policy Prerequisites]
* xref:oauth-dance-about.adoc[OAuth 2.0 Dance and OAuth 2.0 Access Token Enforcement]
* xref:apply-oauth-token-policy-task.adoc[Applying an OAuth 2.0 Token Validation Policy]
* xref:using-policies.adoc[Applying a Policy]
* https://www.pingidentity.com/en/products/pingfederate.html[PingFederate] identity provider
* xref:access-management::external-identity.adoc#instructions-for-saml-configuration[SAML 2.0]
* xref:3.8@mule-runtime::mule-expression-language-mel.adoc[MEL expressions]
* xref:configure-autodiscovery-4-task.adoc[Configuring API Gateway API Autodiscovery in a Mule 4 Application]
* xref:configure-autodiscovery-3-task.adoc[Configuring API Gateway API Autodiscovery in a Mule 3 Application]
