= About Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This file is obsolete

== See Also

* xref:policies-landing-page.adoc[Policies]

////

A policy extends the functionality of an API and enforces certain capabilities such as security. A policy can control access and traffic without modification to the API implementation. Custom policies can provide other capabilities, such as encrypting and logging.

Policies applied to APIs in the latest release of API Manager are the same as those in the earlier release with a few exceptions.

Classloader isolation exists between the application, the runtime and the connectors, and policies. To fulfill the isolation requirement, policies are self-contained and packaged to include libraries needed for execution, similar to an application.

Policies are non-blocking. You can order all policies except CORS which takes precedence over others.

== See Also

* xref:policies-whats-new-concept.adoc[What's New in Policy Management]
* xref:tutorial-manage-an-api.adoc[To Apply a Policy and SLA Tier]

////