= Simple Security Manager Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Simple Security Manager policy lets you configure a security manager with a username and password that you can define at the policy level.

== Prerequisites

This document assumes that you are an API Versions Owner for the API version that you want to manage, or that you are a member of the Organization Administrators role.

== How Does This Policy Work?

This policy acts as a simple security manager for you to test validations against your APIs using a username and password that you define when configuring your policy.

When setting up this policy, you need to send requests to your APIs using a basic authentication mechanism specifying the username and password that you previously configured.


== Policy Configuration

[%header%autowidth.spread,cols="a,a"]
|===
| Element | Description
| *Username*
| The username that your simple security manager policy uses to authenticate your requests.

| *Password*
| The password that your simple security manager policy uses to authenticate your requests.
|===

== See Also

* xref:policy-mule3-ldap-security-manager.adoc[LDAP Security Manager]
