= To Re-order Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This procedure describes how to re-order policies provided by Anypoint Platform other than CORS, Throttling, and Rate Limiting policies. These policies have the highest precedence. If you apply these policies, you cannot set other policies at a higher level. You can set the order of execution of policies for a custom policy by configuring the policy tag or the before or after blocks.

. In Anypoint Platform, click API Manager, and in API Administration, click the API version.
. On the API version details page, choose Policies.
. In the top of the list of any applied policies, click Edit Policy Order to change the priority.
. In Reorder Applied Policies, use the up and down arrows to rearrange the order of policies. For example, if you apply rate limiting, IP whitelist, and XML threat protection, you can reorder only the IP whitelist and XML threat protection policies because rate limiting takes precedence over the other policies.
. Click Apply order.

== See Also

* xref:applying-custom-policies.adoc#order-property-in-policy-tag[Policy tag in a custom policy]
* xref:applying-custom-policies.adoc#order-property-in-before-and-after-tags[Before or after blocks]