= Promoting an API Instance to Another Environment 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before promoting an API instance to another environment:

. Have the `Manage APIs Configuration` permission to promote an API.
. Have the `Access Management` permission to set permissions for viewing and managing an entity.

You can only promote an entity (Policies, Alerts, and more) if you have both permission to view the source and to manage the destination over each entity. Typical view permissions include `View API Configuration` and `View Policies`, as explained in xref:environment-permission-task.adoc[To Grant Permission to Access Environments]. 

Set the permissions as needed before proceeding to the following steps:

include::partial$task-promote-api.adoc[]

Promoting an API instance affects only the API definition, not the existing deployed applications subscribed to the instance. After promoting an API, the *API Label* remains the same, but the *API Instance ID* changes.

For existing applications that need to subscribe to a promoted API:

. Update the *API Instance ID* within the application.
. Because each environment has a different client ID and secret, update the application's client ID and secret.

== See Also

* xref:environment-permission-task.adoc[Granting Permission to Access an environment]
* xref:access-management::environments.adoc[Environments]
* xref:create-instance-task.adoc[Creating an API instance on API Manager]