= Promoting an API Instance to Another Environment 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before promoting an API instance to another environment, ensure that you have the `Manage APIs Configuration` permission.

You can only promote an entity, such as policies or alerts, if you have both the permissions to view the entity and to manage its destination. For example, you must have the `View Policies` and `Manage Policies` permissions to promote a policy. 

To promote an API instance:

include::partial$task-promote-api.adoc[]

Promoting an API instance affects only the API definition, not the existing deployed applications subscribed to the instance. After promoting an API, the *API Label* remains the same, but the *API Instance ID* changes.

For existing applications that must subscribe to a promoted API instance:

. Update the *API Instance ID* within the application.
. Because each environment has a different client ID and secret, update the application's client ID and secret.

== See Also

* xref:environment-permission-task.adoc[Granting Permission to Access an environment]
* xref:access-management::environments.adoc[Environments]
* xref:create-instance-task.adoc[Creating an API instance on API Manager]