= Promoting an API Instance to Another Environment 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

A tight integration of Anypoint Platform components extends the use of environments to API management. In this procedure, you change the environment of an API.

You must have `Manage APIs Configuration` permission to promote an API and `Access Management` permission to set permissions for viewing and managing an entity. You can only promote an entity (Policies, Alerts, and so forth) if you have permission to view the source and permission to manage the destination over each entity. Typical view permissions are `View API Configuration` and `View Policies`, as explained in xref:environment-permission-task.adoc[To Grant Permission to Access Environments]. Set the permissions as needed before proceeding.

. Select *API Manager > API Administration > Add API > Promote API from environment*.
. For *Source Environment*, select the environment of the API to promote.
. For *API*, enter the name of the API and then select it from the APIs in the source environment.
. For *API Version*, select the version of the API.
. Optionally, for *API instance label*, select the API instance name if you created any instances.
. Select or deselect entities to include in the promotion: Policies, SLAs, Alerts, and API Configuration.
. Optionally, if your external client provider differs in the environment to which your are promoting the API, select the provider in the *Client provider* list.
. Click *Promote*.

Promoting an API affects only the API definition, not the existing deployed applications subscribed to the API. After promoting an API, the API Name remains the same, but the API ID changes.

For existing applications that need to subscribe to a promoted API, you need to make the following changes:

. Update the API ID.
. Because each environment has a different client ID and secret, update the application's client ID and secret.

== See Also

* xref:environment-permission-task.adoc[Granting Permission to Access an environment]
* xref:access-management::environments.adoc[Environments]
* xref:create-instance-task.adoc[Creating an API instance on API Manager]