= Deploy Your API Proxy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: proxy-deploy-cloudhub-latest-task.adoc, proxy-deploy-hybrid-latest-task.adoc, proxy-deploy-runtime-fabric.adoc

You can deploy your API proxy to CloudHub, Runtime Fabric, or a hybrid cloud environment. The resources allocated to the proxy application varies based on the type of proxy you are using. For example, the CloudHub proxy includes a CPU with 0.1 vCores and a memory of 500 MB, by default. 

If required, modify the resource allocation from xref:runtime-manager::deploying-to-cloudhub#change-settings-of-a-deployed-application.adoc[Runtime Manager].

== Prerequisites

Before you deploy your API proxy, complete the following requirements if you work in a Runtime Fabric or hybrid cloud environment:

* Runtime Fabric
** Obtain the Manage APIs Configuration and Deploy API Proxies permissions on your account.
** Use Mule versions 3.8.7, 3.9.1, 4.1.2, or later.
* Hybrid: 
** For private servers, obtain access to a Mule runtime engine (Mule) instance configured for your organization. 
+
For information about how to configure a Mule instance as a server, see xref:runtime-manager::servers-create.adoc[register a server in Runtime Manager].
** Register your private server with a Mule agent that is compatible with your Mule instance.
+
For Mule versions 3.8 and later, use Mule Agent 1.9.0. For Mule 4.x, use the Mule Agent specified in the release notes. 

== Deploy Your API Proxy

Deploy your proxy by completing the following steps:

include::partial$task-add-api-instance.adoc[tags=proxy-first-steps;target-type;mid-steps;asset-type-options;proxy-downstream;proxy-upstream;last-steps]

If you are deploying your API to a Mule 4 environment and want to enable the proxy to support HTTPS requests, first xref:building-https-proxy.adoc[build HTTPS API proxies].

If you deployed your API to a Mule 3 environment, xref:enable-https-mule3-proxies.adoc[enable HTTPS in Mule 3x].

== See Also

* xref:https-reference.adoc[Configuring an HTTPS Endpoint]
