= To Modify a Proxy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In most cases, the proxy you generate in API Manager is suitable for deployment out of the box. However, you can modify the proxy to log data to a file or send data to a Splunk account with the Anypoint Splunk Connector, for example. To inspect or change a proxy application, import the proxy application in http://www.mulesoft.com/platform/mule-studio[Anypoint Studio]. You can modify the application to perform additional functionality, provided essential structures remain in place. This section shows skeletal XML examples of several types of proxy applications having the essential structures.

To inspect the essential structures of a proxy application:

. After setting up a proxy using API Manager, in the Status area, click one of the *Download proxy* options.
+
. In Studio, select *File* > *Import*.
. In the Import dialog, expand the *Mule* node, and select *Anypoint Studio Generated Deployable Archive (.zip)*. Click *Next*.
. Navigate to a proxy zip file that you downloaded from API Manager.
. Click *Finish*.

You can now edit the proxy application.

The downloaded file is a deployable proxy application. If needed, modify the downloaded zip file to adjust for port conflicts, use shared connector resources, or include custom code for logic that you want to add to the proxy. Deploy the proxy application. After deployment, the yellow circle in the status indicator turns green.