= To Configure Multiple Workers
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This file is obsolete.

////
In a CloudHub multi-worker environment, you need to ensure that all workers can validate the OAuth token issued to a particular worker. You also configure the idempotent filter to stop duplication of the token on those workers. The token store by default uses an in-memory object store that is not shared between the workers in a Cloudhub deployment. A reference to the `_defaultUserObjectStore` implements the object store provided by CloudHub such that all workers share this object store.

. In the OAuth provider app configure the object store:
+
[source,xml,linenums]
----
    <spring:bean name="tokenStore" class="org.mule.modules.oauth2.provider.token.ObjectStoreTokenStore">
        <spring:property name="refreshTokenObjectStore" ref="_defaultUserObjectStore" />
        <spring:property name="accessTokenObjectStore" ref="_defaultUserObjectStore" />
    </spring:bean>

	<oauth2-provider:config name="external-oauth2-provider"
		...
		tokenStore-ref="tokenStore">
	</oauth2-provider:config>
----
+
. Add the idempotent filter configuration to your application:
+
[source,xml,linenums]
----
<idempotent-message-filter idExpression="#[message:id]" throwOnUnaccepted="true" storePrefix="someprefix" >
  <spring-object-store ref="_defaultUserObjectStore"/>
</idempotent-message-filter>
----

After deployment, all workers share, but do not duplicate, the same token store.

== Next

link:/api-manager/to-deploy-provider[To Deploy the Provider to a Remote Server].
////