
//tag::intro[]
After you have created an API using Design Center or any other application, you can then manage that API in API Manager by adding an API instance.

There are three options for adding an API instance:

* <<add-new-api, *Add new API*>> + 
Select this option to add a completely new instance of an API.
* <<promote-api, *Promote API from environment*>> Select this option if you have an API instance in a different environment, for instance
the sandbox environment, and you want to promote it to the current or production environment.
* <<import-api, *Import API from zip file*>> Select this option if you have exported an API instance from a different Anypoint Platform
instance.

When you are promoting or importing an API instance, you do not have options to alter the configuration. However,
when you add a new API instance, you need to xref:configure-api-task.adoc[configure the endpoint] as well as other settings.

//end::intro[]

Mule Gateway:: Select Mule Gateway if you have APIs on Mule Runtime that need an API gateway to manage, observe,
and secure your APIs.
+

Service Mesh:: Select Service Mesh to extend Anypoint Platform API Management capabilities to your
Istio service mesh through the deployment of a Mule Adapter.

//tag::promote-api[]
[[promote-api]]
== Promote API from Environment

. Navigate to *Anypoint Platform* > *API Manager*. 
. In *API Administration*, click **Add API** and select **Promote API from environment**.
. Select the **Source Environment**.
. Select the **API** by entering the name of the API into the search field.
. Select the **API Version**.
. Select the **API instance label**.
. Optionally, uncheck any of the **Include in Promotion** options you want to exclude.
. Click **Promote**.
. Review and update the Runtime & Endpoint Configuration details as needed and click **Save**.

//end::promote-api[]

//tag::import-api[]
[[import-api]]
== Import API from Zip File

. Navigate to *Anypoint Platform* > *API Manager*.
. From *API Administration*, click **Add API** and select **Import API from zip file**.
. Click **Choose file** and select your API instance configuration zip file.
. Click **Next**.
. Review and update the API Configuration details as needed and click **Save**.
//tag::import-api[]